### ISSUE TITLE
Cannot build rainmeter with visual studio 2015

### ISSUE THREAD

**Issue by JayHawel** [rainmeter/rainmeter#101]
I can't bulid rainmeter with visual studio 2015.  Platform Toolkit  needs vs2017(v141), when I used VS2015 to compile it ,  VS said cannot find v141.  Eventually, I build rainmeter with VS2017

**Comment by brianferguson** [comment]
We upgraded the build process to VS2017 a few weeks ago. https://github.com/rainmeter/rainmeter/commit/e4b25adb6f86e4c3a1c39224381440b87331c36d

If you want to still use VS2015, you need to change this line back to `v140`. You may need to revert [this](https://github.com/rainmeter/rainmeter/commit/2fa44ad64313eb852327571f5e332f97fb169a3a) back as well in you are using the build batch file.

We are in the process of updating the build instructions.

-Brian

**Comment by JayHawel** [comment]
Thank you!
