### ISSUE TITLE
Can't open .ini file when use the relative path.

### ISSUE THREAD

**Issue by Doracoin** [rainmeter/rainmeter#103]
In "Rainmeter.ini"，I set the "SkinPath=.\Skins". The skin is loaded normally, but when I "EditSkin", notepad tips "Path not exsit..." Blabla.............
Is it suggestion not to use relative path?

**Comment by Doracoin** [comment]
It is on version 4.0.0.

**Comment by brianferguson** [comment]
Yes, SkinPath needs to be an absolute path and not a relative path.

-Brian
