### ISSUE TITLE
!CommandMeasure bang with formulas passes string value not formula result

### ISSUE THREAD

**Issue by tjhrulz** [rainmeter/rainmeter#104]
The documentation says that bangs are a legal place to use a formula and gives this example
`LeftMouseUpAction=[!SetOption SomeMeter W "((2.5 + 100) * 2)"]` 
While this example works it is because meter options are a legal place to use a formula, the option will be set to the string "((2.5 + 100) * 2)". Thus if you use a bang to set something that does not accept a formula or expect to get the result 205 and not a formula string you would need to use a calc instead and pass the reference to the calc. The documentation should include the caveat as the created a mild headache for me the other day as I had assumed I was using a bad formula.

**Comment by tjhrulz** [comment]
My apologies I seem to have gotten this one slightly wrong, it seems this may just be effecting the  !CommandMeasure bang as it seems !WriteKeyValue and !SetVariable set it to the result and not the formula string. Ill try to check all the other bangs tomorrow to see if it is just the one or if there are more affected by this.

**Comment by jsmorley** [comment]
Given that !CommandMeasure can be and is used to pass formulas to a .lua script, it would be difficult indeed to pre-parse and resolve formulas embedded in a !CommandMeasure string.

I do not believe that [!SetVariable SomeVar "(20 + 15)"] would set the value of the variable SomeVar to "35", but would literally set it to the string "(20 + 15)". It would be the responsibility of where you "use" that #Variable# to resolve it to the result.

**Comment by tjhrulz** [comment]
Yeah I think I popped into the chat the one day and we talked about this, either that or I talked with Azack about it one day and I just forgot to close the issue on here. Want me to go on ahead and do that/you can go on ahead and close it.
