### ISSUE TITLE
Regression in r2822 in RecycleManager

### ISSUE THREAD

**Issue by thatsIch** [rainmeter/rainmeter#111]
I just downgraded to r2821 from June 29, 2017 to check if it works again.

I have a skin using the `RecycleManager` and the `OnChangeAction` to trigger a meter update and redraw. This worked in **r2821** but stopped working in **r2822** and **r2824**.  In order to update the skin I either have to refresh the skin, Rainmeter or open the RecycleBin.

Here are the skin files to reproduce:
* https://github.com/thatsIch/Minimal/blob/develop/Dock/Bin/Bin.ini
* https://github.com/thatsIch/Minimal/blob/develop/%40Resources/Measures/Dock/Bin/RecycleManager.inc

If required, I can compile a more minimalistic version.

Cheers, Ich

**Comment by brianferguson** [comment]
I can't reproduce this in r2821, r2822 or r2824. The RecycleManager plugin hasn't changed in years.

Maybe related to [this](https://forum.rainmeter.net/viewtopic.php?p=138029#p138029) issue?

-Brian

**Comment by thatsIch** [comment]
No, I rarely restore files. 

Did maybe Windows 10 change in that regard? 
As it seems, this is also unreliable in r2821. I just deleted files, watched the recycle bin and it went up from 14 to 15 files but the `RecycleManager` still reports **5** files.

After I get home from work, I will create a clonable skin which reproduces this on my machine. 

Cheers, Ich

**Comment by jsmorley** [comment]
I am unable to replicate this. The RecycleManager measure seems to work exactly as expected.

As long as you are adding things to the recycle bin, it properly detects them, including any OnChangeAction. If you empty the bin, it also properly reacts to that.

The only anomaly, which is a known issue, is that it won't detect when you restore items from the bin. It only detects "add" and "empty". 

4.1.0 beta r2833 64-bit (Jul 11 2017)
Windows 10 Pro 64-bit (build 15063)
Path: C:\Program Files\Rainmeter\
IniFile: C:\Users\Jeffrey\AppData\Roaming\Rainmeter\Rainmeter.ini
SkinPath: C:\Users\Jeffrey\Documents\Rainmeter\Skins\

**Comment by thatsIch** [comment]
Since this is event based, is there a possibility that the event is dropped? I get inconsistent behavior and I don't think that Rainmeter is at fault, but for example even refreshing all Rainmeter skins did not let the plugin report the correct file count nor file size. I am not sure why this is happening; it never happened before the last win 10 update.

Since I cannot reproduce this consistently I will close this and will keep looking at it in case I get some clue.

---

dummy skin using: https://pastebin.com/kNWuqG9t
