### ISSUE TITLE
Unhandled exception in v4.1.0.2838

### ISSUE THREAD

**Issue by r-Larch** [rainmeter/rainmeter#117]
Hallo,
I have this skin installed "SystemInformation" and if i start CPU_OHM.ini then Rainmeter v4.1.0.2838 throws an unhandled exception and closes and i can not start it again without removing the OpenHardwareMonitorPlugin.dll Plugin. I think Rainmeter should not crash if a Plugin crashes.

Visual Studio Debug msg:
Exception thrown at 0x00007FFF3B924231 (OpenHardwareMonitorPlugin.dll) in Rainmeter.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

[Skin-SystemInformation.zip](https://github.com/rainmeter/rainmeter/files/1220147/Skin-SystemInformation.zip)

```ini
; Maybe relevant lines:

[Variables]
WinB=Fintek F71889F
MCPU=AMD Phenom II X4 965 BE

; CPU Clocks from OpenHardwareMonitor
[OHMCPUFreq]
Measure=Plugin
Plugin=Plugins\OpenHardwareMonitorPlugin.dll
Hardware=#MCPU#
Type=Clocks
Sensor=CPU Core #1

; CPU Voltage from OpenHardwareMonitor
[OHMCPUVID]
Measure=Plugin
Plugin=Plugins\OpenHardwareMonitorPlugin.dll
Hardware=#WinB#
Type=Voltages
Sensor=CPU VCore

; CPU Temp from OpenHardwareMonitor
[OHMCPUTemp]
Measure=Plugin
Plugin=Plugins\OpenHardwareMonitorPlugin.dll
Hardware=#MCPU#
Type=Temperatures
Sensor=Core #1 - #4
```

I ran this on  PC with Intel CPU

**Comment by brianferguson** [comment]
We can't prevent a Rainmeter crash if a 3rd party plugin crashes. Please contact the author of the OpenHardwareMonitorPlugin.dll for help on this matter.

-Brian
