### ISSUE TITLE
AudioLevel: DeviceList is getting cutoff when multiple devices are present

### ISSUE THREAD

**Issue by MarcoPixel** [rainmeter/rainmeter#120]
The output of the audiolevel devicelist measure is getting cutoff mid-string and won't show more audio devices. This won't allow Fountain of Colors and Monstercat Visualizer to fully show all audio devices propertly in their audio device pickers.

**Skin:** https://gist.github.com/MarcoPixel/8d8913fe853a797c24c6ff83205080a6
**Screenshot:** 
![image](https://user-images.githubusercontent.com/3743025/29493519-67b01986-8598-11e7-846b-706395d0744e.png)

**Comment by brianferguson** [comment]
I increased the buffer from 512 characters to 4096 characters. Hopefully this will be enough.

-Brian

**Comment by MarcoPixel** [comment]
Great, thanks for the quick fix :)
