### ISSUE TITLE
Scaled image drawing issue

### ISSUE THREAD

**Issue by hyrious** [rainmeter/rainmeter#140]
I made a background.png by:
```
B: #000f W: #ffff T: #0000
BBBBB
BWWWB
BWTWB
BWWWB
BBBBB
```
Then used it as a meter's background with mode 3 (center scaled), wishing its center 1x1 transparent pixel would be scaled to fill the background center.
```ini
[Rainmeter]
update=1000
Background=#@#Background.png
BackgroundMode=3
BackgroundMargins=2,2,2,2
[Label]
meter=String
Text=Emmm..
FontColor=255,120,120,255
FontFace=Consolas
FontSize=22
Antialias=1
```
But I got: 
![result](https://user-images.githubusercontent.com/8097890/32890709-dea814b4-cb0a-11e7-99ec-10a60a946782.png)
Borders are well, yet center looks wrong. I then tried other numbers to `BackgroundMargins`, but no works.

Then I made a slight bigger one (6x6, with center 2x2 transparent),  it works with and only with
```ini
BackgroundMargins=2,2,3,3
```

![result2](https://user-images.githubusercontent.com/8097890/32890860-75848840-cb0b-11e7-91a8-231398f3c3ee.png)

I think there might be a slight adjustment in drawing the center image, then I looked into source code:
https://github.com/rainmeter/rainmeter/blob/master/Library/Skin.cpp#L2496
https://github.com/rainmeter/rainmeter/blob/master/Common/Gfx/Canvas.cpp#L438

It was drawed by GDI+. That's all I know.

**Comment by brianferguson** [comment]
Sorry this took so long to reply to. This was fixed when we converted from GDI+ rendering to D2D rendering.

-Brian
