### ISSUE TITLE
Hyper-V machines?

### ISSUE THREAD

**Issue by Suncatcher** [rainmeter/rainmeter#165]
Does Rainmeter support showing info about the Hyper-V VMs I have in my system? Which of them running, which are not and their IPs?

**Comment by brianferguson** [comment]
It may be possible to get their IP's with the [SysInfo](https://docs.rainmeter.net/manual-beta/plugins/sysinfo/) plugin using the name of the adapter for [SysInfoData](https://docs.rainmeter.net/manual-beta/plugins/sysinfo/#SysInfoData) (assuming Hyper-V VM's add a virtual adapter to the IP table, which I have no idea if it does).

If the VM outputs any log or status file, you could parse it for its 'status' via WebParser. Or, if there is some command that you can run with RunCommand, or a value in the Registry that can be queried. Those would be the only ways I can think of to get the 'status' of a VM.

-Brian
