### ISSUE TITLE
change in aspect ratio makes relative placement between skins behave unconsistent

### ISSUE THREAD

**Issue by tmnvnbl** [rainmeter/rainmeter#179]
## description
Going from an ultrawide resolution to a regular widescreen places some skins in an expected location, but other skins are places in a whole other location. Especially the relative distance between skins is changed, making the nice look of a setup look rather bad. Happens also when going from regular aspect ratio to ultrawide aspect ratio.

## screenshots
Intended placement
![capture20180702225258152](https://user-images.githubusercontent.com/40273626/42185912-edcfafc6-7e4a-11e8-93cf-80cc820a6948.png)
Switch to ultrawide
![capture20180702225239322](https://user-images.githubusercontent.com/40273626/42185913-edf240cc-7e4a-11e8-8374-47064e5b6890.png)

**Comment by brianferguson** [comment]
I suspect the bottom skin is utilizing its position from the right edge of the screen, while the top skin is not. You can control this by manually setting the `WindowX`/`WindowY` options in **Rainmeter.ini**, utilizing the `R` syntax.
[https://docs.rainmeter.net/manual/settings/skin-sections/#WindowXY](https://docs.rainmeter.net/manual/settings/skin-sections/#WindowXY)

Another alternative is use a "screen" variable like the [default layout](https://github.com/rainmeter/rainmeter/blob/master/Build/Layouts/illustro%20default/Rainmeter.ini#L5) does. Basically, you subtract the width of your skin from the [SCREENAREAWIDTH](https://docs.rainmeter.net/manual/variables/built-in-variables/#SCREENAREAXYWH) variable.

For more specific help, please visit the forums!
[https://forum.rainmeter.net/](https://forum.rainmeter.net/)

-Brian
