### ISSUE TITLE
Skins cannot be placed at the bottom

### ISSUE THREAD

**Issue by lovelytangming** [rainmeter/rainmeter#186]
I am a user,my computer has Fences 3 installed, this will conflict with the Rainmeter, Rainmeter skins will not be placed at the bottom of the fences, this will look very awkward, that is, the bottom option in the posotion in the bottom priority setting seems not low enough,thinks.

![snipaste_2018-08-11_00-15-43](https://user-images.githubusercontent.com/39945960/43969249-0c94d38a-9cfc-11e8-929b-a93c3009f950.png)

**Comment by brianferguson** [comment]
The 'bottom' z-order position setting for skins only places the skin window as the bottom-most window in **relation** to other windows, not items drawn directly on the desktop. 'Fences' is not drawing to it's own window, but to the desktop itself (or it is replacing the desktop window itself).

There is nothing Rainmeter can do about it.

-Brian
