### ISSUE TITLE
soundcloud and spotify

### ISSUE THREAD

**Issue by tarbear123** [rainmeter/rainmeter#187]
i think that you should update the simple media player to show sound cloud and spotify

**Comment by Malavos** [comment]
Dear @tarbear123 ,

what?

I mean, could you describe better your problem? Do you need spotify and soundcloud integration, is that it?

**Comment by brianferguson** [comment]
This doesn't feel like an issue at all, but more of a feature request for either a skin, or for NowPlaying.
Spotify is partially supported by the NowPlaying measure. https://docs.rainmeter.net/manual/measures/nowplaying/#playerlist

There is also a plugin that might help. https://forum.rainmeter.net/viewtopic.php?p=139011#p139011

If the "issue" is about some skin called "simple media player", then please contact its author about your question(s).

-Brian
