### ISSUE TITLE
[feat] Add `Unload` item to folder context menu

### ISSUE THREAD

**Issue by usernamehw** [rainmeter/rainmeter#193]
Just started with the app. Probably missing an obvious way to unload a skin.

But expected place for me to unload all from a skin is there:
![screenshot 115](https://user-images.githubusercontent.com/9638156/49792567-1ebb6080-fd44-11e8-9d47-5b19dac5ec9d.png)

**Comment by brianferguson** [comment]
You have a folder selected there...not a skin. If you select a skin that is loaded and right click on it, there is an "Unload" item in the context menu.

There is also a big "Unload/Load" button just to the right above the "Metadata".

You can also right click on the skin itself and select "Unload skin" (the last item).

-Brian

**Comment by usernamehw** [comment]
Well, that's the point of the proposed feature: to unload all skins from a folder. 

I installed a skin `Circle Launcher` => and it took a huge dump on my desktop creating a lot of shortcuts (each of them is a skin). It would be user-friendly to have a way to unload all that.

At this point I know that it's possible to create empty layout and load it. But it's different since it will unload every skin from each folder.
