### ISSUE TITLE
NowPlaying.dll - Appdata and the Windows Store

### ISSUE THREAD

**Issue by goldenpipes** [rainmeter/rainmeter#196]
Hello there!

I use the Windows Store version of MusicBee and have been using the nowplaying.dll to parse from MusicBee to display CD Art from the player to my rainmeter skin.

MB writes to `C:\Users\NAME\AppData\Local\MusicBee\InternalCache\` and nowplaying.dll parses that. 

For some reason, Track 1 album art does not show up. Track 2 and beyond show perfectly fine.  

The problem relates to `C:\Users\NAME\AppData\Local\MusicBee\InternalCache\` not existing as the store app writes to `C:\Users\USER\AppData\Local\Packages\50072StevenMayall.MusicBee_kcr266et74avj\LocalCache\Local\MusicBee\InternalCache\' (This is a sandboxing feature of the windows 10 store app system)

Why does nowplaying.dll not read the "Packages" appdata on track 1 but it does on track 2+?

in the meantime i have made a symlink for `C:\Users\NAME\AppData\Local\MusicBee\InternalCache\` to point to `C:\Users\USER\AppData\Local\Packages\50072StevenMayall.MusicBee_kcr266et74avj\LocalCache\Local\MusicBee\InternalCache\'

And it works fine. just curious if this is a known issue with store version of apps with their funky appdata folders.

MusicBee forum bug report:
https://getmusicbee.com/forum/index.php?topic=28020.0

Ill try to get some logs from rainmeter as well as MB. Cheers!

**Comment by brianferguson** [comment]
https://getmusicbee.com/forum/index.php?topic=28020.0#msg155695

-Brian
