### ISSUE TITLE
AudioPulsarRay drawer

### ISSUE THREAD

**Issue by IHydrogeNI** [rainmeter/rainmeter#197]
![image](https://user-images.githubusercontent.com/22572854/54546698-48c09680-49b5-11e9-9635-07d3d4b78a79.png)

there is no problem while using rainmeter 4.2. 
looks like a drawer code working false

**Comment by eclectic-tech** [comment]
Maximum Ring Depth should not exceed the diameter (twice the Radius value), I will add a clamp to limit the user input value of the Ring Depth in an update. Thanks for reporting.
