### ISSUE TITLE
Documentation: WebParser and Rainmeter.data

### ISSUE THREAD

**Issue by Gozer-404** [rainmeter/rainmeter#202]
Hello,

As I had to "fight" with `Rainmeter.data` to understand how to set the `ProxyServer` value in it (and found the answer only by looking at the code) could you please add in the documentation the "complete" format for setting this value in `Rainmeter.data` aka something like:

> [WebParser.dll]
> ProxyServer=localhost:8080
> UserAgent=Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0)

**Comment by brianferguson** [comment]
[Commit](https://github.com/rainmeter/rainmeter-docs/commit/6098e9bf9f648ffe2433c3eb2ae219b4f8de6543)

[Docs](https://docs.rainmeter.net/manual/measures/webparser/#ProxyServer)

-Brian
