### ISSUE TITLE
Show widgets in a separate window

### ISSUE THREAD

**Issue by xmha97** [rainmeter/rainmeter#205]
Hello, I don't like to see my widgets on the desktop.
Please add the below feature:
Show widgets in a separate window (like Windows 11)
![image](https://user-images.githubusercontent.com/23485114/147964167-8a1d93bc-2efc-489e-86f7-f2a279781a51.png)

**Comment by xmha97** [comment]
@brianferguson Is it possible to implement this feature?

**Comment by brianferguson** [comment]
We have no plans to do this.

-Brian
