### ISSUE TITLE
Click on System Tray Icon to Toggle Game Mode

### ISSUE THREAD

**Issue by amirrammari** [rainmeter/rainmeter#213]
Hello Rainmeter Team
Please add below feature:
- Click on System Tray Icon to Toggle Game Mode

**Comment by brianferguson** [comment]
Thank you for the suggestion, however, clicking on the tray icon will always open the Manage dialog - and we will not be changing it's behavior. This is a critical feature of Rainmeter and is used very often with our support community.

-Brian
