### ISSUE TITLE
Functional-style dynamic generation of meters

### ISSUE THREAD

**Issue by JordyScript** [rainmeter/rainmeter#214]
Would it be possible to add a meter that can repeat itself for every item in a collection / list? Kind of like how map or apply would work on an array in functional programming. This would greatly simplify working with variable amounts of data.

For example, if one wanted to show the contents of a directory on the filesystem, every directory will have a variable amount of contents, but usually you want to render every individual item in the exact same way.

There are hacky ways around this, but they are complex, and native support is gonna be a huge benefit.

**Comment by brianferguson** [comment]
This has come up several times in the past. The real problem with "real-time" meter creation is coming up with a clear and concise syntax that a very basic user can follow. Most users (and skin authors) are not programmers and following "programmer-like" code can be a big challenge.

We certainly welcome any user-submitted PR's for review from those who want to tackle a project like this, but the Rainmeter team is going to focus on other projects.

-Brian
