### ISSUE TITLE
Make containers nestable

### ISSUE THREAD

**Issue by xXNicksonXx** [rainmeter/rainmeter#223]
Im currently working on a skin, where im using the container option for meters. I tried to nest some containers in an other container, but it didnt work. Then I saw this: `Containers may not be "nested"` on [Rainmeter](https://docs.rainmeter.net/manual/meters/general-options/container/). Would it be possible to change that?

**Comment by brianferguson** [comment]
Unfortunately, it isn't possible at this time. IIRC, the issue was the resources it took to draw masked items for each layer (ie. container) at low update values.

-Brian
