### ISSUE TITLE
(Suggestion) More transparency options

### ISSUE THREAD

**Issue by Hairetik0s** [rainmeter/rainmeter#227]
I'd like always on top + always visible + high transparency to be less intrusive, but the transparency options only move in 10% increments, and 90% transparent is still a bit too opaque. Any chance we could go to 5% increments or ideally just type in whatever percentage we want? Not critical, but the flexibility would be nice.

**Comment by brianferguson** [comment]
If we did 5% increments, it would double the size of the context menu, which is probably undesirable in most situations. We are in the very early discussions about changes to the Manage dialog, so we may look at this when ideas are ironed out.

In the meantime, you can manually add/edit the `AlphaValue` option for the skin in the [settings file](https://docs.rainmeter.net/manual/settings/). This is a value from 0 (transparent) to 255 (opaque).
[https://docs.rainmeter.net/manual/settings/skin-sections/#AlphaValue](https://docs.rainmeter.net/manual/settings/skin-sections/#AlphaValue)

You can also use the `!SetTransparency` bang to control this setting from within a skin.
[https://docs.rainmeter.net/manual/bangs/#SetTransparency](https://docs.rainmeter.net/manual/bangs/#SetTransparency)
Example (in the `[Rainmeter]` section of your skin): `OnRefreshAction=[!SetTransparency "12"]`

-Brian
