### ISSUE TITLE
Help me to create a widget with the system-wide theme.

### ISSUE THREAD

**Issue by xmha97** [rainmeter/rainmeter#235]
Hello Rainmeter developers
Please help me to create a widget with the system-wide theme.

![Chrome-Canary-dark-mode-Windows-10](https://user-images.githubusercontent.com/23485114/84064127-63769500-a9d7-11ea-9b91-7d742f177b57.gif)

I want the widget background to match the theme.

In this way, in the light theme, the background of the widget will be white.
And in the dark theme, the background of the widget will be black.

Also please see the issue below:
https://github.com/MinhThienDX/win10widgets/issues/30
There is information that may be helpful.

Thanks.

**Comment by brianferguson** [comment]
This isn't the appropriate place for help with skins. Please post your questions here:
[https://forum.rainmeter.net/viewforum.php?f=5](https://forum.rainmeter.net/viewforum.php?f=5)

-Brian

**Comment by xmha97** [comment]
Thanks and sorry for that.
