### ISSUE TITLE
Why don't you use a junction link or symbolic link (aka symlinks) instead of AppData EXE?

### ISSUE THREAD

**Issue by xmha97** [rainmeter/rainmeter#236]
Why don't you use a junction link or symbolic link (aka symlinks) instead of AppData EXE?
Like `%LocalAppData%\Microsoft\WindowsApps\`
![image](https://user-images.githubusercontent.com/23485114/84572654-d6558680-adb0-11ea-8b82-1b7360266c88.png)

Read more about junction link or symbolic link:
https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/

_Originally posted by @xmha97 in https://github.com/rainmeter/rainmeter/issues/221#issuecomment-643639228_

**Comment by brianferguson** [comment]
https://github.com/rainmeter/rainmeter/issues/221#issuecomment-644538291-permalink

-Brian
