### ISSUE TITLE
Illustro partially installed in r3410

### ISSUE THREAD

**Issue by backerman** [rainmeter/rainmeter#241]
According to the beta documentation, the install should include the Illustro skin, but it's only partially installed. There are some assets in `Defaults\Skins` and `Defaults\Layouts` but there's no indication that the skin is installed in the UI.

Reproduction:

1. On a system without Rainmeter installed, download and install Rainmeter-4.4-r3410-beta.exe using the default settings.
2. After the install completes, it starts Rainmeter, which displays an error that no skins are available.

Observed with Win10 Pro 20H2 build 19042.630.

**Comment by brianferguson** [comment]
When Rainmeter starts it looks for your [skins folder](https://docs.rainmeter.net/manual/installing-rainmeter/#DefaultFileLocations). If no skins are found in your skins folder, Rainmeter will copy the default illustro skins from `Defaults\Skins` folder to your **skins** folder.

1. Try restarting Rainmeter again to see if there was some sort of delay in copying the default illustro skins to your skins path.
2. Manually check if the illustro skins are installed. For standard installations, Rainmeter should place them in your user Documents folder. `%USERPROFILE%\Documents\Rainmeter\Skins\`
3. If there is no `illustro` folder, then the most likely cause is your antivirus program is preventing Rainmeter from creating that folder. Windows Defender has something called  "Controlled folder access". If this is ON, then programs like Rainmeter cannot write to the Documents folder. Other antivirus programs might have something similar. You may need to create an exception for Rainmeter.

If all else fails, you could try following the following guide and try re-installing again. [https://docs.rainmeter.net/tips/clean-rainmeter-uninstall/](https://docs.rainmeter.net/tips/clean-rainmeter-uninstall/)

-Brian
