### ISSUE TITLE
Variable files overwritten when Merge skins is selected in package installer

### ISSUE THREAD

**Issue by mpurses** [rainmeter/rainmeter#242]
I need to be able to merge (not delete user created files, because I let them create presets for Themes/Visualizers) AND preserve their variables upon upgrading a skin.
  
  
Looking at the docs and the code give conflicting info. This says it should preserve variables:
https://docs.rainmeter.net/tips/advanced-rmskin-options/
> **Both Variables files and Merge skins:**
> One or more .ini (or .inc) files are listed in Variables files, and Merge skins is checked.
> **Result:**
> Both actions are done.
> Can be used used to change a skin .ini file while leaving existing variable values set by the user unchanged.
> Can be used to add lines to a .inc file, while leaving existing variable values set by the user unchanged.
  
  
But the Rainmeter code does not seem to allow it:
https://github.com/rainmeter/rainmeter/blob/7bd5279964f3302be53c84a2e83a0dde947f21fa/Library/DialogInstall.cpp#L856-L859

![installer](https://user-images.githubusercontent.com/642218/100241530-67e92880-2ef9-11eb-8fda-407cf0b463c1.png)

**Comment by brianferguson** [comment]
I have responded to the forum topic linked below. Please continue the discussion in that thread.

[https://forum.rainmeter.net/viewtopic.php?f=14&t=36289&p=187428#p187428](https://forum.rainmeter.net/viewtopic.php?f=14&t=36289&p=187428#p187428)

Thanks,
-Brian
