### ISSUE TITLE
ESET Rainmeter Log - PHP/WebShell.NJN trojan

### ISSUE THREAD

**Issue by SHHSSH** [rainmeter/rainmeter#243]
Last night I received warnings from ESET in regards to Rainmeter.

Now I know it's continually proclaimed that there are no potential security vulnerabilities within Rainmeter but if you could just brief these logs I'd apprecaite your feedback.

Let me know if you need anymore info.

Thanks.

http://www.filedropper.com/rainmeteresetlog

File Details:
Filename: RainmeterEsetLog.xml
Size: 7129.41666667 KB, Type: xml

**Comment by brianferguson** [comment]
Judging by your .xml file, it looks like some feed you are downloading via Rainmeter's Webparser measure is the culprit, not the Rainmeter executable itself. See the named "column" tag `Object` items in your .xml file.

Here is the latest virustotal.com scan results of the latest release of Rainmeter (4.3.1.3321):
[https://www.virustotal.com/gui/url/eab775a9e612eecb66af2fd8b8d0ef3e565b46c6480e3975b861b1678104837b/detection](https://www.virustotal.com/gui/url/eab775a9e612eecb66af2fd8b8d0ef3e565b46c6480e3975b861b1678104837b/detection)

And here is the latest scan results for the latest beta release of Rainmeter (4.4.0.3410):
[https://www.virustotal.com/gui/url/c2f5336e193a09a8f0f76fd9ef8e98c54f338d2fa883ad68f379078db7b0371e/detection](https://www.virustotal.com/gui/url/c2f5336e193a09a8f0f76fd9ef8e98c54f338d2fa883ad68f379078db7b0371e/detection)

If you need some help on identifying the skin that is downloading the "bad" feed, you can post a message on our help forums here: [https://forum.rainmeter.net/viewforum.php?f=4](https://forum.rainmeter.net/viewforum.php?f=4)

-Brian
