### ISSUE TITLE
Add and Set theme in rainmeter api ( c# )

### ISSUE THREAD

**Issue by ASVIEST** [rainmeter/rainmeter#245]
reload and apply  rainmeter  theme in c#

**Comment by brianferguson** [comment]
I don't think this is a good fit for the Rainmeter API. Layouts can be loaded via the `!LoadLayout` bang. Saving a Layout is as simple as copying the settings file `Rainmeter.ini` to the Layouts folder (and refreshing then Rainmeter).

-Brian
