### ISSUE TITLE
Weather not working - can't connect

### ISSUE THREAD

**Issue by AngelTs** [rainmeter/rainmeter#246]
This plug in is the part of the main program, but not working at this time

**Comment by brianferguson** [comment]
This isn't a Rainmeter issue, it is the weather website that is the problem.
More information can be found here: [https://forum.rainmeter.net/viewtopic.php?f=134&t=34689](https://forum.rainmeter.net/viewtopic.php?f=134&t=34689)

If you need help with fixing the skin, you can for help here: [https://forum.rainmeter.net/viewforum.php?f=5](https://forum.rainmeter.net/viewforum.php?f=5)

-Brian

**Comment by AngelTs** [comment]
Why include not working Weather module in the main package - "Win10-Widgets.Rainmeter-4.0.exe"?
It is a false advertisement!!!

**Comment by brianferguson** [comment]
Rainmeter only comes with the default illustro skins. Win10 Widgets is from a 3rd party. I would not recommend getting Rainmeter from anywhere other than https://rainmeter.net

-Brian

**Comment by AngelTs** [comment]
Sorry for my critic. I determine what is the problem - i downloaded "Win10.Widgets_1.0.0.rmskin" from tjmarkham, not from rainmeter. Thank you so much for your detailed help and support!
