### ISSUE TITLE
Timestamp=epoch return wrong Day and Year

### ISSUE THREAD

**Issue by AngelTs** [rainmeter/rainmeter#247]
Timestamp=1608976802 return wrong Day and Year

Example:

[MeasureChild2]
Measure=WebParser
URL=[MeasureSite]
;1608976802
StringIndex=5

[MeasureTimeLocal]
Measure=Time
TimeStamp=[MeasureChild2]
Format=%#H:%M, %m/%d/%Y
DynamicVariables=1

Produce:
Saturday, 27 December 1651 10:00:02
The correct is:
Saturday, 26 December 2020 10:00:02

**Comment by brianferguson** [comment]
That is a Unix timestamp, not a Windows timestamp.

[https://docs.rainmeter.net/manual/measures/time/#TimeStamp](https://docs.rainmeter.net/manual/measures/time/#TimeStamp)

-Brian

**Comment by AngelTs** [comment]
Resolution- add the following line:

[MeasureTimeLocal]
...
Timestamp=(([MeasureChild2])+11644473600)
...

Thanks!
