### ISSUE TITLE
Rainmeter CPU usage too high

### ISSUE THREAD

**Issue by agentvei** [rainmeter/rainmeter#249]
From what I've heard, Rainmeter uses very little CPU. However, my Rainmeter uses about 38% of my CPU

![image](https://user-images.githubusercontent.com/77443565/105141969-83a13180-5b2c-11eb-8eed-bfb07040aaed.png)

I only have a few skins loaded and it's already using 38%. Can someone help me find a way to decrease it?

I have a Intel Core i5-2450M 2.50 GHz

![image](https://user-images.githubusercontent.com/77443565/105142258-fca08900-5b2c-11eb-8a92-45109d3dfac9.png)

**Comment by brianferguson** [comment]
You will have to identify which skin is the culprit. Try unloading one skin at a time and watch your CPU usage. There may be more than 1 skin causing this.

In most cases, skins uses a very low [Update](https://docs.rainmeter.net/manual/skins/rainmeter-section/#Update) rate are the cause of high CPU usage. They are usually "visualizer" type skins.

We don't normally provide skin support here on github, so once you find the offending skin, please ask for help on our forums. [https://forum.rainmeter.net/viewforum.php?f=5](https://forum.rainmeter.net/viewforum.php?f=5)

Thanks,
-Brian
