### ISSUE TITLE
Rainmeter spawning a lot of processes

### ISSUE THREAD

**Issue by willemdh** [rainmeter/rainmeter#256]
Rainmeter seems to spawn a huge amount of processes, is this normal?

For example an overview of all cmd.exe processes spawned by Rainmeter over 30 days on 1 endpoint....

![image](https://user-images.githubusercontent.com/6462991/108258675-95dcb280-7160-11eb-9b22-46e2cb1366bb.png)

**Comment by brianferguson** [comment]
Rainmeter does not spawn any process by itself. However, a skin can call any program at any time using actions or plugins.

Judging by your picture, it looks like one of your skin(s) invokes some command(s) at regular intervals. Search through your running skins to find the culprit.

You can post a message [here](https://forum.rainmeter.net/viewforum.php?f=5) if you need more help.

-Brian
