### ISSUE TITLE
[INVESTIGATION] Something is wrong with the release binaries building environment.

### ISSUE THREAD

**Issue by Nodens-** [rainmeter/rainmeter#260]
Since I moved to a CPU with 36 logical cores I have been having an issue with the last 4 cores not producing any readings no matter what plugin I used.
The log shows for all 4 cores when I use `Measure=CPU`:
`CPU: Processor=33 is not valid (CSM\Cybernetic System Monitor\CPU_GPU\CPU.ini - [Mse_Core_33])`

I have finally found some free time and decided to debug the issue myself. So I cloned the repo and set 2 breakpoints. One on `LogWarningF(this, L"CPU: Processor=%i is not valid", processor);` in `void MeasureCPU::ReadOptions(ConfigParser& parser, const WCHAR* section)"` that produces the log output and one on `c_NumOfProcessors = (int)systemInfo.dwNumberOfProcessors;` in `void MeasureCPU::InitializeStatic()` because it is apparent from `ReadOptions()` that something is wrong with the value of `c_NumOfProcessors` (and I know already that systemInfo.dwNumberOfProcessors is returning the proper value on my system as I had tested this when I first met the issue).

I built the debug x64 build and tried to run it under the debugger in VS2019 IDE but it wouldn't autoload my skin for some reason, I run it without the debugger for testing and voila. Attached the debugger to the running process, reloaded the skin. I checked the log and to my great surprise the log output was not there. I looked at the skin output and, weirdly enough, the last 4 cores were getting proper readings.
I killed the process and run the freshly installed `4.4 Beta Release - r3445` again. The issue was there once more. I thought that maybe something with the debugging libs so I decided to test the release x64 target. Again no issue whatsoever.

So my initial assessment is that there's something wrong with the building environment of the released binaries. I am building on my software engineering workstation, with VS2019 toolchain. 

It is 2am and have to get up early in the morning so I just wanted to post this, before going to bed, in case anyone, actually familiar with the project, has any insights. I'll continue the investigation tomorrow afternoon and update.

**Comment by Nodens-** [comment]
Ok I found out what was going on. Apparently the files that were getting installed by the installer were the x86 version for some weird reason: 
![Capture](https://user-images.githubusercontent.com/2942378/115061641-1cf49f80-9ef2-11eb-8ce0-1eaa7703d450.JPG)

Notice this was in `Program Files` as a normal x64 installation, not in `Program Files (x86)`. My installation has been updated with the installer update option forever. Not sure how the installer figures out what target to install when it upgrades (I'm assuming by checking the binary?) or when and if that behavior changed at some point but apparently it kept throwing the x86 target in the x64 directory. Once I manually deleted the binaries, the installer behaved as doing a fresh installation, producing the x64 toggle with it marked as default. The x64 binaries behave exactly like the ones I built myself so apparently this is a x86 limitation and making an educated guess, it's probably that `systemInfo.dwNumberOfProcessors` just returns 32 as max value for 32bit targets and not an actual bug.

I am leaving this open in case someone wants to check installer behavior.

**Comment by brianferguson** [comment]
What probably happened is on the very first installation of Rainmeter, the checkbox "Install 64-bit version" was unchecked. The installer then installed the 32-bit version in the `%PROGRAMFILES%\Rainmeter` folder, even though this folder is normally for 32-bit installations. The "Install 64-bit version" checkbox does not change the folder to the (x86) folder for 32-bit installations when not checked. (BTW - that checkbox should have been checked by default on 64 bit systems).

Subsequent installations look for an installed version and select the same 32-bit or 64-bit version as the previous installation. You will not see a checkbox as long as there is a previous normal installation on the system.

You can test this by deleting the `%PROGRAMFILES%\Rainmeter` folder, then reinstall Rainmeter. You will see a "Install 64-bit version" checkbox and it should be checked. If you uncheck it and continue to install Rainmeter, the installation folder will still be in `%PROGRAMFILES%' folder, not the (x86) folder. If you then run the install again, you will not see the "Install 64-bit version" checkbox at all.  - If you test this all over again, but make sure that "Install 64-bit version" is checked, then run the installer again, the 64-bit version will be installed everytime going forward.

-Brian

**Comment by Nodens-** [comment]
@brianferguson Hello Brian. This explanation sounds plausible and thanks for the explanation on the installer implementation. The first installation was back when there was no x64 version if I remember right. Perhaps something was wrong during the initial migration to x64. I'm very careful with installers, I doubt I could ever leave a x64 checkbox unchecked as I spend a lot of time checking installer options carefully on anything I install. But I guess anything is possible. Perhaps I was working too many hours straight or it was too early in the morning. Things can happen.

You should consider using the `%PROGRAMFILES(x86)%` variable when installing x86 target on x64 as this implementation is out of spec. It would have saved me quite a bit of time debugging the binaries without symbols, heh. It completely escaped me to check for bitness, as I'd never expect 32bit binaries in 64bit directory, until I switched to x64dbg for analysis and it was then that I noticed. Also it may be a good idea to publish the symbols in a separate zip along with the releases so that debugging of running targets is a lot easier :)
