### ISSUE TITLE
Add detect maximized window

### ISSUE THREAD

**Issue by azhe403** [rainmeter/rainmeter#261]
Currently here available Full-screen mode for games/apps and detect process list. Look good if detect maximized window too.
Sory bad my english.

![gambar](https://user-images.githubusercontent.com/17938038/115510424-e92ac880-a2a9-11eb-9f6d-f35987049e0e.png)

**Comment by brianferguson** [comment]
The team discussed this, and we decided to not check for maximized windows.

-Brian
