### ISSUE TITLE
V. 4.5.0 has several security flags on VirusTotal

### ISSUE THREAD

**Issue by nnagata** [rainmeter/rainmeter#272]
Hello. Just wanted the community/devs to be aware of this.  

I downloaded the .exe file from the main [rainmeter homepage](https://www.rainmeter.net/) download link which redirects to this address:

> https://github.com/rainmeter/rainmeter/releases/download/v4.5.0.3518/Rainmeter-4.5.0.exe

I uploaded the Rainmeter-4.5.0.exe file on [VirusTotal](https://www.virustotal.com/gui/home/upload) and several security flags appear in the results. I initially tried this about 12 to 18 hours ago. At that time only the `BScope.Trojan.CoinMiner` appeared in the results. (Oddly the bitcoin mining doesn't bother me a ton...)

I tried again very recently and now `Artemis!E0E7A4F2DACA` appears.  Here's a [link to the results in the screenshot] below. (https://www.virustotal.com/gui/file/e501fd184ffe7186b133df8302e97f19b21d8c225326eb7f7ece6c5d049453e6/detection)

![Screenshot 2021-08-29](https://user-images.githubusercontent.com/4470749/131285068-c28dd2c6-855c-4f21-a0d7-c47fd616d06e.png)

My security expertise is very limited so just take the information at face value. My intention is mostly so devs are aware of this. I wasn't sure if email was the best way to reach out since I'm not sure how often the team@rainmeter.net email is checked or who has access to it, and this information seems likely time sensitive.

Been using Rainmeter for over 10 years - love the project! I'll continue using an older version of Rainmeter for now until more information is available. :)

**Comment by brianferguson** [comment]
This seems like a temporary hiccup from McAfee. I just ran the scan again, and only the VBA32 scan remains.
[https://www.virustotal.com/gui/file/e501fd184ffe7186b133df8302e97f19b21d8c225326eb7f7ece6c5d049453e6/detection](https://www.virustotal.com/gui/file/e501fd184ffe7186b133df8302e97f19b21d8c225326eb7f7ece6c5d049453e6/detection)
![Screenshot 2021-08-30 at 00-53-12 VirusTotal](https://user-images.githubusercontent.com/1591640/131298002-b67c935a-abea-498b-b608-b7a63b8f5e28.png)


While I am not sure as to why VBA32 would flag Rainmeter as a bitcoin miner, it could be related our certificate used to "sign" our binary files. The "corporate name" Rainmeter uses in the certificate is called `Firebit OÜ`, and IIRC, the certificate file itself uses ANSI encoding, thus converting the `Ü` to a `U`. Unfortunately, there seems to be a Brazilian bitcoin exchange company with a similar name. This _might_ be the cause of incorrect flag.

More information:
[https://forum.rainmeter.net/viewtopic.php?f=103&t=33142](https://forum.rainmeter.net/viewtopic.php?f=103&t=33142)
[https://github.com/firebit-ou](https://github.com/firebit-ou)

Anyway, thanks for being a long time user, and also the heads up about the VirusTotal results! We appreciate your feedback!

-Brian

**Comment by SaberAkiyama** [comment]
Jiangmin AV had virus detected
![Screenshot (214)](https://user-images.githubusercontent.com/48464326/142344949-dcc594cc-ce90-413d-9c17-a3fa2290ac49.png)

And this on AdvancedCPU and WifiStatus DLL files are detected by Cylance
![Screenshot (215)](https://user-images.githubusercontent.com/48464326/142344990-f9cd258a-95e6-4f00-a34f-08ca906a253f.png)

**Comment by brianferguson** [comment]
Thanks for reporting, however, these are also false positives.

-Brian
