### ISSUE TITLE
Extend support for AIMP4

### ISSUE THREAD

**Issue by deathcrafter** [rainmeter/rainmeter#282]
https://github.com/rainmeter/rainmeter/blob/c62be50e140b963ba05e49ec180fddd3d6643864/Library/NowPlaying/PlayerAIMP.cpp#L302

Do you think we should add another if block for AIMP4?

Reference: https://forum.rainmeter.net/viewtopic.php?t=38835

**Comment by brianferguson** [comment]
I don't have AIMP installed, could you confirm a couple of items for me?

1. Does the registry key `HKLM\SOFTWARE\Microsoft\CurrentVersion\Uninstall\AIMP4\DisplayIcon` exist? And if yes, what is its value?
2. Is the executable name `AIMP4.exe` ? If not, could you provide an image snapshot of all the values under `HKLM\SOFTWARE\Microsoft\CurrentVersion\Uninstall\AIMP4` ?

Thanks,
Brian

**Comment by deathcrafter** [comment]
I will, once I return home to my PC. Thanks for responding.

**Comment by deathcrafter** [comment]
While searching for the above I found out something interesting.

When a 32-bit app is run in a 64-bit system, it is written under a subkey `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node`, e.g. my installation of AIMP3 is under this:
`HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\AIMP3`

And also, AIMP4 and up are simply using AIMP, without version suffixed to them.
So we should do something like this to check where the actual keys are located:
```C++
void PlayerAIMP::OpenPlayer(std::wstring path)
{
	if (path.empty())
	{
		// Check for AIMP2 first
		DWORD size = 512;
		WCHAR* data = new WCHAR[size];
		DWORD type = 0;
		HKEY hKey;

		std::wstring keyadress;

		// If system is 32 bit, this function raises "ERROR_CALL_NOT_IMPLEMENTED" error. Picked up from: https://stackoverflow.com/a/59287159/17028991
		UINT is64 = GetSystemWow64Directory(NULL, 0);

		if (GetLastError() == ERROR_CALL_NOT_IMPLEMENTED)
		{
			keyadress = L"SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\";
		}
		else
		{
			keyadress = L"SOFTWARE\\WOW6432Node\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\";
		}

		bool executed = false;

		RegOpenKeyEx(HKEY_LOCAL_MACHINE,
			(keyadress + L"\\AIMP3").c_str(),
			0,
			KEY_QUERY_VALUE,
			&hKey);

		if (RegQueryValueEx(hKey,
			L"DisplayIcon",
			nullptr,
			(LPDWORD)&type,
			(LPBYTE)data,
			(LPDWORD)&size) == ERROR_SUCCESS)
		{
			if (type == REG_SZ)
			{
				path = data;
				path.resize(path.find_last_of(L'\\') + 1);
				path += L"AIMP3.exe";
				ShellExecute(nullptr, L"open", path.c_str(), nullptr, nullptr, SW_SHOW);
			}
			delete[] data;
			RegCloseKey(hKey);
			return;
		}

		// Let's try AIMP3
		RegCloseKey(hKey);

		RegOpenKeyEx(HKEY_LOCAL_MACHINE,
			(keyadress + L"\\AIMP3").c_str(),
			0,
			KEY_QUERY_VALUE,
			&hKey);

		if (RegQueryValueEx(hKey,
			L"DisplayIcon",
			nullptr,
			(LPDWORD)&type,
			(LPBYTE)data,
			(LPDWORD)&size) == ERROR_SUCCESS)
		{
			if (type == REG_SZ)
			{
				path = data;
				path.resize(path.find_last_of(L'\\') + 1);
				path += L"AIMP3.exe";
				ShellExecute(nullptr, L"open", path.c_str(), nullptr, nullptr, SW_SHOW);
			}
			delete[] data;
			RegCloseKey(hKey);
			return;
		}

		// Let's try AIMP2
		RegCloseKey(hKey);
		RegOpenKeyEx(HKEY_LOCAL_MACHINE,
			(keyadress + L"\\AIMP2").c_str(),
			0,
			KEY_QUERY_VALUE,
			&hKey);

		if (RegQueryValueEx(hKey,
			L"DisplayIcon",
			nullptr,
			(LPDWORD)&type,
			(LPBYTE)data,
			(LPDWORD)&size) == ERROR_SUCCESS)
		{
			if (type == REG_SZ)
			{
				ShellExecute(nullptr, L"open", data, nullptr, nullptr, SW_SHOW);
			}
		}

		delete[] data;
		RegCloseKey(hKey);
	}
	else
	{
		ShellExecute(nullptr, L"open", path.c_str(), nullptr, nullptr, SW_SHOW);
	}
}
```

Although the values in WOW6432Node gets copied into the usual registry location, it's unreliable since I didn't notice the change right after installation.

And I was not sure about the `keyadress` variable name. So you can change it to something Rainmeter-ish.

Also, notice that I altered the order of version checking in AIMP, giving priority to latest version, since AIMP, AIMP3 and AIMP2 can be installed side-by-side.

**Comment by deathcrafter** [comment]
Opened a pull request with proposed changes after testing.
https://github.com/rainmeter/rainmeter/pull/283
