### ISSUE TITLE
NUM_MONITORS not returing correct monitor count

### ISSUE THREAD

**Issue by sveco** [rainmeter/rainmeter#284]
Using SysInfo measure to get monitor count, actual monitor caount is 2, but it lists all GPU ports as connected, see image.

Rainmeter 4.5.4.3550 (64-bit)
Language: English (1033)
Build time: 2021-10-04  9:25:19
Windows 10 Pro 2009 64-bit (build 19043) - English (1033)

Even with no other plugin loaded, still same issue.

![image](https://user-images.githubusercontent.com/2922684/142061071-f7a9bbb6-670e-44ee-86d3-840a74397055.png)

EDIT: GPU is NVIDIA GTX 1060 6GB,
output of:  Get-CimInstance -Namespace root\wmi -ClassName WmiMonitorBasicDisplayParams

Active                        : True
DisplayTransferCharacteristic : 120
InstanceName                  : DISPLAY\DEL415A\5&112faf11&0&UID28931_0
MaxHorizontalImageSize        : 60
MaxVerticalImageSize          : 34
SupportedDisplayFeatures      : WmiMonitorSupportedDisplayFeatures
VideoInputType                : 1
PSComputerName                :

Active                        : True
DisplayTransferCharacteristic : 120
InstanceName                  : DISPLAY\IVM560C\5&112faf11&0&UID28930_0
MaxHorizontalImageSize        : 52
MaxVerticalImageSize          : 29
SupportedDisplayFeatures      : WmiMonitorSupportedDisplayFeatures
VideoInputType                : 1
PSComputerName                :

**Comment by brianferguson** [comment]
I am unable to reproduce your issue. `NUM_MONITORS` works for me.

Here is the code I used (similar to yours):
``` ini
[Rainmeter]
AccurateText=1
BackgroundMode=2
SolidColor=111111

[Count]
Measure=SysInfo
SysInfoType=NUM_MONITORS

[Meter]
Meter=String
MeasureName=Count
FontColor=FFFFFF
FontSize=84
Padding=5,5,5,5
AntiAlias=1
Text=Monitor Count: %1
```

Could you turn on [Debug mode](https://docs.rainmeter.net/manual/user-interface/manage/#SettingsTab) (and "Debug to file") and then restart Rainmeter and copy the relevant monitor log information here?

Thanks,
-Brian

**Comment by sveco** [comment]
Attaching log. But I think I found out what is the issue. Current monitor count is calculated, and monitor count returns 4, instead of 2 as it should. I only have two monitors attached, but graphic card has 4 ports. Lately i updatedd firmware on GPU to support booting into BIOS on display port, and i think this has caused GPU to report all ports as active, even if only two have attached cable.
[Rainmeter.log](https://github.com/rainmeter/rainmeter/files/7538573/Rainmeter.log)

**Comment by sveco** [comment]
Now the question is : can I get count of only active monitors?

**Comment by sveco** [comment]
I uploaded the updated image - the real problem is that the monitor count is 4 instead of 2, which would be correct. Calc measure was then working wrong (it expected max 2 monitors). It looks like NUM_MONITORS is returning all available HDMI/DisplayPorts instead of actual connected monitors.

**Comment by brianferguson** [comment]
I fixed this for the next release. Thanks for reporting!

-Brian

**Comment by sveco** [comment]
Works, thank you 👍
