### ISSUE TITLE
Registry measure appears unable to read values larger than 4096 bytes

### ISSUE THREAD

**Issue by njascgil** [rainmeter/rainmeter#289]
I was being unable to read the contents of the following key
`HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\PendingFileRenameOperations`

At first, I thought that the problem was with the value type "REG_MULTI_SZ" which, strictly speaking, is not one of the three supported key value types. However, after finding out that other values of type "REG_MULTI_SZ" could indeed be read, I narrowed down this issue to the size/length of the key, which was way above 4096 bytes. After truncating the value contents just below 4096 bytes, the Registry measure was again able to correctly read its contents.

I'm not sure if this behaviour is by design (there are probably few registry values of interest this large). However, this issue also impacts correctly finding out if a value just exists, as the Registry measure returns "0" for both an inexisting value or a value longer that 4096 bytes.

**Comment by brianferguson** [comment]
Thanks for the bug report! This has been addressed.

I also replaced the null separators (for `REG_MULTI_SZ` types) with a newline character for display purposes.

Just a quick note, that particular registry item's size can be very, very long (longer than you could possibly display on your screen). You might want to limit what your skin displays to the screen. Also, that registry item seems to include 0 length items in some cases, so you will end up with extra newline characters - so you may want to substitute a double newline with a single newline in your measure. Something like this: `Substitute="#CRLF##CRLF#":"#CRLF#"`

-Brian
