### ISSUE TITLE
Can't install on standard user

### ISSUE THREAD

**Issue by xmha97** [rainmeter/rainmeter#294]
Hi, I can't install Rainmeter on the standard user.
Please make an installation for the current user/all users.
![image](https://user-images.githubusercontent.com/23485114/149637898-eb52337d-afc2-41f5-951d-4ffd8514e329.png)
![image](https://user-images.githubusercontent.com/23485114/149637918-a791a190-0516-4a8e-8ccf-ccb6742d96b4.png)
Thanks.

**Comment by brianferguson** [comment]
Obviously this isn't Rainmeter, but something called Simplenote.

-Brian

**Comment by xmha97** [comment]
> Obviously this isn't Rainmeter, but something called Simplenote.

This was an example installer that would be installed for both the current user and all users.
That's the problem:

The issue is that I can't install the Rainmeter in the unelevated users.
![image](https://user-images.githubusercontent.com/23485114/149641939-205aa64b-a422-4e4d-862e-2171476945af.png)
![image](https://user-images.githubusercontent.com/23485114/149641931-274623ee-40cd-45e0-ab11-a1b157ba6feb.png)

**Comment by deathcrafter** [comment]
> This was an example installer that would be installed for both the current user and all users. The issue is that I can't install the Rainmeter in the unelevated users.

Try the portable installation
