### ISSUE TITLE
Command Line for GameMode Toggle

### ISSUE THREAD

**Issue by xmha97** [rainmeter/rainmeter#295]
How I can toggle game mode using the command line?

My suggested commands:
```powershell
"C:\Program Files\Rainmeter\Rainmeter.exe" --game-mode-toggle
```
```powershell
"C:\Program Files\Rainmeter\Rainmeter.exe" --game-mode-start
```
```powershell
"C:\Program Files\Rainmeter\Rainmeter.exe" --game-mode-stop
```

**Comment by brianferguson** [comment]
You can't. Game mode is designed to be triggered in 3 ways:

1. Manually by the user by selecting the "Game mode" context menu via the Rainmeter context menu.
2. Selecting the "Full screen games" checkbox (Manage dialog). This will allow Rainmeter to monitor the "state" of other windows, and if a game goes into full screen mode, Rainmeter will trigger some action you set. Note: Not all games will work with this.
3. Adding specific process names to the "Additional process list" listbox. When any process name matches one within that list, Game mode will be triggered.

We will not be adding any way for a skin (or other means) to automate the triggering of Game mode.

-Brian
