### ISSUE TITLE
Command Line for "Manage Skins"

### ISSUE THREAD

**Issue by xmha97** [rainmeter/rainmeter#298]
I need a command line for "Manage Skins"
For example:
```
"C:\Program Files\Rainmeter\Rainmeter.exe" -manage
```
I want to add a context menu to my desktop (like Windows 7)
![image](https://user-images.githubusercontent.com/23485114/162665537-0d3ff0fb-f52c-4f25-9213-8e01072ae1bb.png)
Thanks.

**Comment by brianferguson** [comment]
You can use the manage bang.
`"C:\Program Files\Rainmeter\Rainmeter.exe" !Manage`

2nd paragraph: [https://docs.rainmeter.net/manual/bangs/](https://docs.rainmeter.net/manual/bangs/)

-Brian
