### ISSUE TITLE
skins not sticking in set position

### ISSUE THREAD

**Issue by Sylvanas-1977** [rainmeter/rainmeter#302]
When you change resolution on main display all stuff moves around to main screen or different locations, i am not sure if rainmeter developer would be able to fix this, as its technically windows bug, it used to be non issue until i started requiring to change resolution for radeon super resolution to work on main screen, technicall the 2e screen never changes resolution but things move around regardless when main display resolution is changed, even tho all stuff is on secondary display

**Comment by brianferguson** [comment]
It's not really a bug in Rainmeter nor Windows. What happens is when the monitor information changes, the overall virtual screen area changes.

Your best bet is to utilize layouts. Save your current layout, then after changing resolutions, reload your saved layout.

-Brian

**Comment by Sylvanas-1977** [comment]
What this makes no sense whatsoever
