### ISSUE TITLE
DesktopWorkArea suddenly changes when opening some programs

### ISSUE THREAD

**Issue by Mistreaper** [rainmeter/rainmeter#303]
## What?
`DesktopWorkArea` suddenly jumps back to normal when opening several programs, most notably OBS Studio and Epic Games Launcher. 

## Do this
Go to `%appdata%/Rainmeter`, edit the `Rainmeter.ini` file and add this to the `[Rainmeter]` section:

```
DesktopWorkAreaType=1
DesktopWorkArea=0,40,0,0
```

Get OBS Studio, launch Rainmeter on startup, and then launch OBS Studio. It should ignore the `DesktopWorkArea` and take up the screen. If it doesn't work, try getting FancyWM. FancyWM could be the issue.

**Comment by Mistreaper** [comment]
Update: this happens to any applications when started up maximized. I don't know why it's hard to implement `DesktopWorkArea` correctly.

**Comment by brianferguson** [comment]
Any program or Windows itself can change the work area at any time. Trying to manage "what the correct work area should be" is basically impossible, thus Rainmeter does not reset the work area once changed while the program is running.

The best you could do is create a "dummy" skin that monitors the work area variables, and if it changes, the skin could manually call the `RestartRainmeter.exe` program (located in the program path), which would cause Rainmeter to restart and re-read the DesktopWorkArea setting.

-Brian
