### ISSUE TITLE
Official Chocolatey package

### ISSUE THREAD

**Issue by TheKnarf** [rainmeter/rainmeter#304]
[Chocolatey](https://community.chocolatey.org/) is one of the most popular package managers for Windows. It would be nice with an official `rainmeter` package. The unofficial `rainmeter` package is [outdated and broken](https://github.com/aronovgj/choco-auto/issues/44).

**Comment by brianferguson** [comment]
We support `winget` and we also support automatic update installations without any package manager. We have no desire to support other forms of automatic updating.

[https://docs.rainmeter.net/manual/installing-rainmeter/#WinGetInstallation](https://docs.rainmeter.net/manual/installing-rainmeter/#WinGetInstallation)
[https://docs.rainmeter.net/manual/installing-rainmeter/auto-update/](https://docs.rainmeter.net/manual/installing-rainmeter/auto-update/)

-Brian

**Comment by TheKnarf** [comment]
I'm less interested in automatic update and more interested in being able to install it as a part of a setup script from PowerShell. `winget` is still buggy / beta, so I was hoping you might reconsider being on the bigger package manager.
