### ISSUE TITLE
RecycleManager OpenBin broken theme on Windows 11

### ISSUE THREAD

**Issue by skittles9823** [rainmeter/rainmeter#305]
It seems like on Windows 11 22H2 calling OpenBin brings up an explorer window with a broken theme.

After doing some testing I've found that running `explorer.exe ::{645FF040-5081-101B-9F08-00AA002F954E}` causes the issue:
![explorer_n9oy7QBNmp](https://user-images.githubusercontent.com/7065700/174483270-c1b458fe-9986-4c16-8b13-229539d5c745.png)

While `start ::{645FF040-5081-101B-9F08-00AA002F954E}` works just fine:
![explorer_DG0vMpsFVu](https://user-images.githubusercontent.com/7065700/174483355-a92d4dca-70f1-4405-8d5d-7a08ac1f91ae.png)

**Comment by brianferguson** [comment]
Sorry this took so long to respond to.

I couldn't replicate this issue, maybe a Windows Update fixed it?

-Brian

**Comment by skittles9823** [comment]
> I couldn't replicate this issue, maybe a Windows Update fixed it?

No worries, a windows update did fix the issue in [Insider Preview build 22622.575](https://blogs.windows.com/windows-insider/2022/08/10/announcing-windows-11-insider-preview-build-22621-575-and-22622-575/) and I completely forgot I made the issue since.
