### ISSUE TITLE
Unsplash Support 

### ISSUE THREAD

**Issue by codehangen** [rainmeter/rainmeter#315]
Hi! I would like to select the wallpaper in the Rainmeter through an api: [Unsplash](https://unsplash.com/). *Is there any api in Rainmeter to connect to Unsplash?*

**Comment by brianferguson** [comment]
This isn't the job of the main Rainmeter app, but it could be accomplished by a skin. Try searching around deviantart or the Rainmeter forums for one. If there isn't a skin out there that does this, I am sure one could be made.

Here is how you can get started with writing your own skin: https://docs.rainmeter.net/manual/getting-started/

-Brian
