### ISSUE TITLE
Flag /AUTOSTARTUP

### ISSUE THREAD

**Issue by gaetan-31** [rainmeter/rainmeter#317]
Hi,

in version 4.5.14, the autostartup indicator does not create the shortcut at startup.

Fully ok in 4.5.13

**Comment by brianferguson** [comment]
I cannot reproduce this. I tried Windows 7, 10 and 11. No changes to this area code have been made in over a year.

Are you using the silent switch? Your command line should look something like this: `Rainmeter-4.5.14.exe /S /AUTOSTARTUP=1`

Maybe a permission issue?

-Brian

**Comment by gaetan-31** [comment]
Hi,

yes i'm unsing silent install.
Testing with local admin and system account and same problem.
