### ISSUE TITLE
Rainmeter crashing when running the multimedia player on Windows 11

### ISSUE THREAD

**Issue by Sword352** [rainmeter/rainmeter#324]
Hey, Rainmeter crashes when we run the multimedia player on Windows 11. I hope its fixed soon.

**Comment by EldritchEevee** [comment]
Rainmeter does not work and is **incompatible** on Windows 11 due to breaking backend UI changes.

**Comment by brianferguson** [comment]
@Sword352
> Hey, Rainmeter crashes when we run the multimedia player on Windows 11. I hope its fixed soon.

I can't replicate this, could you provide a simple example skin, and exact instructions that causes the crash?

-Brian

**Comment by brianferguson** [comment]
@EldritchEevee 
What are you talking about? Rainmeter works fine on Windows 11.

-Brian
