### ISSUE TITLE
Game Mode doesn't load themes

### ISSUE THREAD

**Issue by nikkehtine** [rainmeter/rainmeter#330]
When game mode is active, Rainmeter unloads all skins and refuses to load a custom theme - not only the one that is set to load after game mode is turned on, but also the one you try to load yourself in the "Themes" tab. Disabling game mode makes themes load normally.

I have YourFlyouts and YourMixer skins installed, which I don't want to unload when I open a game.

**Comment by brianferguson** [comment]
Thanks for reporting, however, I believe this has been fixed for the next release.
https://github.com/rainmeter/rainmeter/commit/c47f2a6d67390cc4e10270f2c9f9ac90a2038642

-Brian
