### ISSUE TITLE
UI don't deal with scalled fonts

### ISSUE THREAD

**Issue by Steffanou** [rainmeter/rainmeter#331]
The UI of Manage Rainmaker don't deal with high resolution screen and scalled system fonts :

![image](https://user-images.githubusercontent.com/13609256/209622670-87463f60-ba01-4afc-a736-dceed7481207.png)

**Comment by brianferguson** [comment]
This has been discussed many, many times. #207 #60 #64

Rainmeter is not high DPI aware.

There is a work-around here: https://forum.rainmeter.net/viewtopic.php?t=22272#p118040

-Brian
