### ISSUE TITLE
Rainmeter install confg error

### ISSUE THREAD

**Issue by weiss655** [rainmeter/rainmeter#332]
Hello, writing to tell than error when i install it Couse confing. what i tryed to do, first i think its security settings of windows so i add my user to full control permissions,  second i tryed install different version but end same. 
when i use portable versions icon tray shows icon than rainmeter closes without grafic interface, couple seconds. so my windows 11 has version 21H2 OS build 22000.1335, that's latest for my pc.

https://prnt.sc/vzt6gid_IIib

**Comment by weiss655** [comment]
Rainmeter isnt working with latest windows 11 build, dont opens default layout, it starts for sec and disapiers.

**Comment by brianferguson** [comment]
Duplicate of the following forum bug report. Please continue discussion there.
[https://forum.rainmeter.net/viewtopic.php?t=41797#p212243](https://forum.rainmeter.net/viewtopic.php?t=41797#p212243)

-Brian
