### ISSUE TITLE
DPI Aware Support for High DPI Displays Resolutions

### ISSUE THREAD

**Issue by nvdavsamd** [rainmeter/rainmeter#334]
i was  Very disappointed by rainmeter, such as rainmeter looks terrible, horrible on modern high dpi resolution display !
take a look yourself
gadgets, menu, text all, everything is foggy, blurry, terrible !
![rainmeter looks like shit on high dpi screen](https://user-images.githubusercontent.com/122004809/211482826-0ea66495-5a7b-483c-a651-1c0b6664f0ab.jpg)

Everything on screen is looking terrible just terrible, i had to quit using rainmeter for good !
Still i had to ask why and how is possible for rainmeter developers to not use DPI Awareness !
![dpi](https://user-images.githubusercontent.com/122004809/211483534-19b9858e-418b-449d-b1ff-4755906afc03.jpg)

**Comment by nvdavsamd** [comment]
Here is the Fix !

Application.vcxproj
---------------------------------------------------------------------------------------------------------------------------------------
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="16.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(SolutionDir)Build\VS\Rainmeter.Cpp.Default.props" />
  <PropertyGroup Label="Globals">
    <ProjectGuid>{D2A0903C-E760-4134-AE61-3D55BF8F760C}</ProjectGuid>
    <ConfigurationType>Application</ConfigurationType>
    <TargetName>Rainmeter</TargetName>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.Default.props" />
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.props" />
  <Import Project="$(SolutionDir)Build\VS\Rainmeter.Cpp.props" />
  <ImportGroup Label="ExtensionSettings">
  </ImportGroup>
  <ImportGroup Label="PropertySheets">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
  </ImportGroup>
  <PropertyGroup Label="UserMacros" />
  <ItemDefinitionGroup>
    <ClCompile>
    </ClCompile>
    <Link>
      <SubSystem>Windows</SubSystem>
      <EntryPointSymbol>wWinMainCRTStartup</EntryPointSymbol>
      <AdditionalDependencies>Shlwapi.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
    <PostBuildEvent>
      <Command>if not exist "$(OutDir)Defaults\Skins" xcopy /Q /S /Y ..\Build\Skins "$(OutDir)Defaults\Skins\"
if not exist "$(OutDir)Defaults\Layouts" xcopy /Q /S /Y ..\Build\Layouts "$(OutDir)Defaults\Layouts\"</Command>
    </PostBuildEvent>
    <Manifest>
      <AdditionalManifestFiles>Application.manifest</AdditionalManifestFiles>
      <EnableDpiAwareness Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">true</EnableDpiAwareness>
    </Manifest>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)'=='Release'">
    <ClCompile>
      <RuntimeLibrary>MultiThreaded</RuntimeLibrary>
      <BufferSecurityCheck>false</BufferSecurityCheck>
    </ClCompile>
    <Link>
      <EntryPointSymbol>Main</EntryPointSymbol>
      <IgnoreAllDefaultLibraries>true</IgnoreAllDefaultLibraries>
    </Link>
    <Manifest>
      <EnableDpiAwareness Condition="'$(Configuration)|$(Platform)'=='Release|x64'">true</EnableDpiAwareness>
    </Manifest>
  </ItemDefinitionGroup>
  <ItemGroup>
    <ClCompile Include="Application.cpp" />
  </ItemGroup>
  <ItemGroup>
    <ResourceCompile Include="Application.rc" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Rainmeter.exe.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <None Include="Rainmeter.ico" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Library\Library.vcxproj">
      <Project>{be9d2400-7f1c-49d6-8498-5ce495491ad6}</Project>
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
  </ItemGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" />
  <ImportGroup Label="ExtensionTargets">
  </ImportGroup>
</Project>

**Comment by brianferguson** [comment]
Thanks, but it is a little more complicated than just adding that to the manifest. It will take editing to the all the different dialogs, mouse detection on the skins, etc.

This has been discussed many times: #331 #207 #66 #60

Although I understand this is not the perfect solution, there is a work-around here: https://forum.rainmeter.net/viewtopic.php?t=22272#p118040

This issue on our radar, but none of the developers have had time to work out all the kinks.

-Brian
