### ISSUE TITLE
DPI Awareness

### ISSUE THREAD

**Issue by nvdavsamd** [rainmeter/rainmeter#335]
![GDIScaling](https://user-images.githubusercontent.com/122004809/212036752-26049585-5fae-4b4f-b380-5edbbdc40daa.jpg)
![dpi](https://user-images.githubusercontent.com/122004809/212036782-4b43dcbf-8306-4059-8fe5-4cce334322b0.jpg)
https://blogs.windows.com/windowsdeveloper/2017/05/19/improving-high-dpi-experience-gdi-based-desktop-apps/#Uwv9gY1SvpbgQ4dK.97

**Comment by brianferguson** [comment]
We went over this in #334

It's going to take more than just a manifest change.

-Brian

**Comment by nvdavsamd** [comment]
unsatisfactory answer.
the gui of rainmeter does NOT contain pictures, images or whatever that might be misalignment with my fix !
still the _"It's going to take more than just a manifest change."_ it's just lazy programming.

try the fix !

**Comment by nvdavsamd** [comment]
Ok, no worries.
I understand.
Thanks.
 
With the Visual Studio 2022 Community DPI Aware option, everything works perfect.
The Rainmeter GUI is perfectly aligned and i have 0 errors !

Also the on display gadgets are working perfectly with 0 errors at all, everything is working scale, clicks whatever !
 
However if you are refering to on display gadgets position then this is a different story.
Each person must use this in order to have AUTO-ALIGNMENT on screen on every resolution
WindowX=(#WORKAREAX# + (#WORKAREAWIDTH#)
WindowY=(#WORKAREAY# + (#WORKAREAHEIGHT#)
And voila with DPI Aware ON and with the above in Rainmeter.ini, auto scale on screen is working perfectly for resolution above 1280x720 !
![Clipboard02](https://user-images.githubusercontent.com/122004809/212842254-5e0a613d-b428-4dba-8f67-79f867ce899e.jpg)
