### ISSUE TITLE
Have you considered using Weblate as your Localisation platform?

### ISSUE THREAD

**Issue by SecularSteve** [rainmeter/rainmeter#336]
Seems easier than going through the paces slowly and manually.

It's meant to make everything easier for everybody, including you.
Completely free, and self-hostable.

But that's just a suggestion, if you have your own reasons as to why, I'm sure they're reasonable.

**Comment by brianferguson** [comment]
Thanks for the suggestion. However, we have limited space available from our host (mainly, the forums). Github pages hosts our main site and docs, but not the forums.

While this is intriguing, it isn't clear if you can self-host this software on github pages. At least I couldn't find it.

Honestly, I am not sure if the process of translating would really save us too much time. We are unlikely to have common strings with other projects. Plus it only takes me a few minutes to upload any changes and make edits on the forum pages and localization page.

We will keep this in mind.

-Brian
