### ISSUE TITLE
Network sensor not reporting anything

### ISSUE THREAD

**Issue by alexdelprete** [rainmeter/rainmeter#351]
Hi,

love rainmeter, thanks for for your work.

I have a problem for the network sensor not reporting anything, and I didn't find a way to debug the issue or configuring the network card that is monitored.

I'm using a notebook with the eth port. Any suggestions?

![image](https://github.com/rainmeter/rainmeter/assets/7027842/2c9899d2-82f5-4232-80c2-035cce10e180)

**Comment by brianferguson** [comment]
This is most likely a 3rd party skin issue and not a Rainmeter application issue.

You can ask for community help on the Rainmeter forums here: [https://forum.rainmeter.net/index.php](https://forum.rainmeter.net/index.php)

To get the best help, make sure to include a link to the skin you downloaded or at least the skin .ini code.

-Brian
