### ISSUE TITLE
[Request] Quartz Analog clock

### ISSUE THREAD

**Issue by bandaid** [rainmeter/rainmeter#354]
Looking for a Quartz Analog clock as pictured in the following links. 

https://www.shutterstock.com/video/clip-1031211878-time-on-clock-three-black-red-arrow

https://www.shutterstock.com/video/clip-1030603157-time-lapse-analog-clock-about-12-midnight

**Comment by brianferguson** [comment]
Issues and Pull Requests on Github are for items related the Rainmeter code, not skin code (other than the default illustro skins), skin requests, or just people searching for skins. That is what Google is for. There is also the [Date and Time](https://forum.rainmeter.net/viewforum.php?f=133) forum for this as well.

-Brian
