### ISSUE TITLE
LuaJIT

### ISSUE THREAD

**Issue by facboy** [rainmeter/rainmeter#359]
is there any interest in porting the Lua integration to use LuaJIT instead?

**Comment by brianferguson** [comment]
I believe LuaJIT is fixed on Lua version 5.1 and can't (or won't, I cannot remember which) be upgraded to newer versions of Lua. Coincidentally, Rainmeter is still using Lua 5.1.5, but we may eventually update to a newer version at some point.

I guess we could give an option in the Script measure to which Lua "engine" to use, but unfortunately none of the team members have time to tackle an option like that at this time. If an ambitious someone were to take on that project, we would gladly review any PR they submitted. :slightly_smiling_face:

-Brian

**Comment by facboy** [comment]
well an ambitious someone has it working locally, but LuaJIT needs to be built out of tree (could try bringing it in tree, but they don't recommend that) and then imported via NuGet.
