### ISSUE TITLE
[Bug] Click through option prevents mouse hover options from working

### ISSUE THREAD

**Issue by nopeless** [rainmeter/rainmeter#361]
![image](https://github.com/rainmeter/rainmeter/assets/38830903/f0166029-2508-41f6-8d4b-2c2671bfc076)

I am not sure if this is intentional

If it is not, I am willing to investigate this issue and submit a PR

**Comment by brianferguson** [comment]
It's intentional.
[https://docs.rainmeter.net/manual/settings/skin-sections/#ClickThrough](https://docs.rainmeter.net/manual/settings/skin-sections/#ClickThrough)

-Brian
