### ISSUE TITLE
Recurring Crashes - System.ArgumentException

### ISSUE THREAD

**Issue by arminmiau** [rainmeter/rainmeter#362]
Hello my rainmeeter installation always crashes every few minutes to hours. I've only found an System.ArgumentException error in reliability monitor of windows and it always has been this error causing the crash.
![image](https://github.com/rainmeter/rainmeter/assets/102313440/662a78ee-faac-488b-868e-39b95767a317)

My version info:
Rainmeter 4.5.18.3727 (64-bit)
Language: English (1033)
Build time: 2023-07-31 11:58:37
Windows 11 Home 21H2 (build 22000.1574) 64-bit - English (1033)
Path: C:\Program Files\Rainmeter\
SkinPath: C:\Users\Armin\Documents\Rainmeter\Skins\
SettingsPath: C:\Users\Armin\AppData\Roaming\Rainmeter\
IniFile: C:\Users\Armin\AppData\Roaming\Rainmeter\Rainmeter.ini

**Comment by brianferguson** [comment]
This error is most likely from a 3rd party C# plugin.

What you need to do is identify the offending skin. Unload your skins one by one until Rainmeter no longer crashes (this might take some time depending on how many skins you have open). Once you identify the skin, open that skin in a text editor and search for any plugin references. They will look something like `Plugin=SomePlugin.dll` (with or without the `.dll` part).

Please list all the plugins the skins uses (there could be more than 1).

-Brian

**Comment by arminmiau** [comment]
Just attached to it in Visual Studio, exception comes from `WindowsNowPlaying.dll` which is used by ModularVisualizers, a module of JaxCore.

**Comment by brianferguson** [comment]
Just as I suspected.

Since that plugin isn't part of the main Rainmeter program (or its included plugins), you will have to contact the author of JaxCore, or the plugin author of [WindowsNowPlaying](https://forum.rainmeter.net/viewtopic.php?t=37088#p188919) for help.

-Brian
