### ISSUE TITLE
`[Skin]` in `Rainmeter.ini` should accept `DynamicVariable`

### ISSUE THREAD

**Issue by phu54321** [rainmeter/rainmeter#363]
I'm trying to make a system monitor skin that appears on bottom right, like this.

<img width="215" alt="image" src="https://github.com/rainmeter/rainmeter/assets/775265/7091da3a-62d0-469b-a1b6-253c8c522936">

On `Rainmeter.ini`, I'm positioning the skin with `SCREENAREAWIDTH` and `SCREENAREAHEIGHT` variable.

```
[Corner-se]
Active=1
WindowX=(#SCREENAREAWIDTH#-200)
WindowY=(#SCREENAREAHEIGHT#-270)
ClickThrough=1
Draggable=0
SnapEdges=1
KeepOnScreen=1
AlwaysOnTop=2
HideOnMouseOver=1
AlphaValue=255
```

Unfortunately, these two variables are dynamic, but since `DynamicVariable` cannot be set on `Rainmeter.ini`, I couldn't get `WindowX` to change corresponding to the window dimension change. I need to refresh the skin or the entire Rainmeter on every dimension change. This hurts when I try to swap between portrait and landscape dimension.

----

Sol 1: Allow `SCREENAREAWIDTH` or any dynamic variable to automatically be applied to Rainmeter.ini. This may have compatibility issues on existing skins though.
Soll 2: Let `[Skin]` accept `DynamicVariable` statement, so people can opt-in for automatic skin reposition whenever dynamic window size changes.

**Comment by Joehuu** [comment]
I had the same issue a while ago. I found out that [`Window{X|Y}`](https://docs.rainmeter.net/manual/settings/skin-sections/#WindowXY) accepts percentages and by also utilizing `Anchor{X|Y}, and this was my solution (for any skin size).

```ini
WindowX=100%
WindowY=(#SCREENAREAHEIGHT# - #WORKAREAHEIGHT#)B
AnchorX=100%
AnchorY=100%
```

**Comment by brianferguson** [comment]
It wouldn't make a lot of sense to continually read any the values from `Rainmeter.ini` at some interval. These values can change due to user interaction (by manually dragging the skin, changes within the Manage dialog, or bangs from any skin).

The best solution would be to utilize the WindowX/Y modifiers like @Joehuu suggested...or manually monitor any changes to the dynamic variables themselves with a measure.

It _could_ look something like:
```ini
[ScreenAreaWidth]
Measure=Calc
Formula=#SCREENAREAWIDTH#
DynamicVariables=1
OnChangeAction=[!Move "(#SCREENAREAWIDTH#-200)" "(#SCREENAREAHEIGHT#-270)"]
```
Or something to that effect. You may have to monitor the screen height as well.

-Brian

**Comment by phu54321** [comment]
For anyone who may mattter:

I'm just fully reloading my skin upon dimension change. This works, and the code won't care the exact position I put the widgets on.

```ini
;===================================================================RESIZE UPDATE=
[ScreenAreaWatcher]
Measure=Calc
Formula=#SCREENAREAWIDTH# * 65537 + #SCREENAREAHEIGHT#
DynamicVariables=1
OnChangeAction=[!Refresh]
```
