### ISSUE TITLE
Widget is not loaded on boot

### ISSUE THREAD

**Issue by trmdi** [rainmeter/rainmeter#366]
I'm using this skin: https://github.com/creewick/MontereyRainmeter
Everything works well except that the weather widget does not display the correct data, only zero is displayed. When I restart rainmeter, it displays the data correctly. Tried using my own weather API key but it doesn't help. Not sure if this is Rainmeter's bug or the theme's bug.

**Comment by trmdi** [comment]
A workaround I've just found out is to use Task Scheduler to make a delayed autostart entry for Rainmeter.

**Comment by brianferguson** [comment]
When starting Rainmeter on boot, sometimes Rainmeter starts before your network connection is established, so any webparser measures will fail at first. Once the network connection is up, the next web request from webparser will usually work, but obviously that is dependent on the measure settings from the skin.

Here is some more infomation on how often webparser updates: [https://docs.rainmeter.net/tips/webparser-updaterate/](https://docs.rainmeter.net/tips/webparser-updaterate/)

Looks like a delayed start of Rainmeter is working for you.

-Brian

**Comment by trmdi** [comment]
A delayed start can be problematic. For example, it makes the clock widget delayed too.
Is there a way to automatically update the webparser when the connection is up?

**Comment by brianferguson** [comment]
A better way _might_ be to [disable](https://docs.rainmeter.net/manual/measures/general-options/#Disabled) any Webparser measure you need to delay, and then monitor your internet connection using the SysInfo measure using `SysInfoType=INTERNET_CONNECTIVITY` and `SysInfoData=Best` options.
[https://docs.rainmeter.net/manual/measures/sysinfo/#Network](https://docs.rainmeter.net/manual/measures/sysinfo/#Network)

Once it returns `1`, you should have an internet connection. Use [IfConditions](https://docs.rainmeter.net/manual/measures/general-options/ifconditions/) to [enable](https://docs.rainmeter.net/manual/bangs/#EnableDisableToggleMeasure) any Webparser measures that were previously disabled.

-Brian
