### ISSUE TITLE
infinite powershell.exe popup while rainmeter installed

### ISSUE THREAD

**Issue by InexactChip** [rainmeter/rainmeter#369]
https://github.com/rainmeter/rainmeter/assets/125568534/c9f9ec56-5025-4518-83f3-1779c1be97b1

**Comment by brianferguson** [comment]
Rainmeter itself doesn't open powershell, but a skin can. None of the default illustro skins call powershell.

You will need to find the offending skin and either ask that skin author for help, or ask for help on our [forums](https://forum.rainmeter.net/viewforum.php?f=5) (remember to provide either skin code or a link to the skin).

-Brian
