### ISSUE TITLE
Beautiful tools!! some plugin recommended

### ISSUE THREAD

**Issue by bryanray** [rainmeter/rainmeter#371]
1> Lottaweather 
2> Ageo / Time
3> Vectra / Date
4> SimplePerfMeter
5> Monstercat / visualizer
![image](https://github.com/rainmeter/rainmeter/assets/1768531/a103d18c-5f92-434a-a26e-a6b89a998a75)

**Comment by bryanray** [comment]
the thing is you need to google these plugins... which is kinda pita....
wouldn't it be nice to have all these plugins inside this repository?

**Comment by brianferguson** [comment]
These aren't plugins, they are skins. There are thousands and thousands of them. We can't include them all. Most are on DeviantArt or our own forums. It's not hard to find what you want.

-Brian
