### ISSUE TITLE
[Feature request] Focus Modes

### ISSUE THREAD

**Issue by TecEash1** [rainmeter/rainmeter#372]
An option to add/create different focus modes with different preset skins/wallpapers.

**Comment by brianferguson** [comment]
What do you mean by "focus modes" ?

-Brian

**Comment by brianferguson** [comment]
This already exists.
[https://docs.rainmeter.net/manual/user-interface/manage/#LayoutsTab](https://docs.rainmeter.net/manual/user-interface/manage/#LayoutsTab)

-Brian

**Comment by TecEash1** [comment]
Thank you!
