### ISSUE TITLE
Color Clamping

### ISSUE THREAD

**Issue by HakShak** [rainmeter/rainmeter#38]
After using a measure for each color (http://rainmeter.net/forum/viewtopic.php?f=14&t=20437), I tried to create the long version of Clamp() inline with LineColor, and that works, however, it's extremely unwieldy.

I find it odd that the Color::MakeARGB function seems to accept values above and below 255 and does what seems to be a modulo operation on them. Which may be a by product of casting somewhere within their API.

Is there any reason not to clamp the color range here:

https://github.com/rainmeter/rainmeter/blob/cef43e28a1525c8515a9ee3824399ebd25e75a1a/Library/ConfigParser.cpp#L1266-L1289

I'm not clear if it's a common practice to take advantage of this "looping" pattern.

**Comment by brianferguson** [comment]
The problem was not really in the Clamp function itself, but with the parsing of comma-separated options with multi-arg math functions.

This has been fixed as of the latest beta, so I am closing this issue.

**Comment by HakShak** [comment]
If anyone is curious about an easier work around for this: https://gist.github.com/HakShak/e6225c488b4a1bfea1c0
