### ISSUE TITLE
🐛 Issue | Rainmeter Version Mismatch with Microsoft's Winget

### ISSUE THREAD

**Issue by 8227846265** [rainmeter/rainmeter#381]
Hi, there's an issue with Rainmeter and Winget.

1. The currently listed Rainmeter in Winget is version `4.5.19.3753`.
2. However, the version installed on the Windows App List doesn't include the whole version number but instead uses `4.5.19`.
3. This causes a problem on Winget wherein it thinks version `4.5.19.3753` isn't installed but already is.

Related:
- https://github.com/microsoft/winget-pkgs/issues/167361

**Comment by brianferguson** [comment]
Ah, I see the issue. We recently started using winget-releaser and missed one of the configuration settings.

This will get fixed before the next release (estimated to be in a few days).

In the meantime, it is perfectly ok to re-install the same version of Rainmeter as a previous installed version. So for this particular version ‘winget upgrade‘ is functionally the same as ‘winget install‘.

**Comment by Dragon1573** [comment]
> ❌ Url validation error
>
> - manifests\r\Rainmeter\Rainmeter\4.5.19.3753
>   - https://github.com/rainmeter/rainmeter/releases/download/v4.5.19.3753/Rainmeter-4.5.19.exe
>     - This URL has previously been reported as Malware to [Microsoft Defender SmartScreen](https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview)
>     - If you believe this is in error, you may [file a report](https://feedback.smartscreen.microsoft.com/feedback.aspx?v=6&t=16&result=block&type=top&url=aHR0cHM6Ly9naXRodWIuY29tL3JhaW5tZXRlci9yYWlubWV0ZXIvcmVsZWFzZXMvZG93bmxvYWQvdjQuNS4xOS4zNzUzL1JhaW5tZXRlci00LjUuMTkuZXhl)
>
> _Originally posted by @wingetbot in https://github.com/microsoft/winget-pkgs/issues/167396#issuecomment-2284290136_

Since the installer is blocked by _Microsoft Defender SmartScreen_, we can do nothing to resolve the problem. Any newer version might face to the same issue and can't be submitted to the repository. 😞
