### ISSUE TITLE
os.date format crashes rainmeter app

### ISSUE THREAD

**Issue by ryanlath** [rainmeter/rainmeter#383]
I was trying to see if I could remove a leading zero from a date, but just trying it, crashes rainmeter.  

In a lua script that works otherwise, this crashes the whole app.
```
-- It's the "#" that does it.
local foo = os.date('%#d', os.time())
```

I would expect an error message, not crashing the whole program?

**Comment by brianferguson** [comment]
We just fixed that recently [here](8a37186d732aa39bafc0900cb498dce2f7f5ef69), and re-applied it [here](e26e10a0324419897b48f7a6a30c244d733082ab) (literally just a few hours ago).

We still have a few things to sort out, before a release is made, but it will be shortly. Hang tight.

-Brian
