### ISSUE TITLE
UAC pop up?

### ISSUE THREAD

**Issue by tspearconquest** [rainmeter/rainmeter#385]
Hello! I am a long time rainmeter user, and have always had automatic updates for it turned on. This morning, while Windows was starting up, I received a UAC prompt to allow Rainmeter to make changes to my system. I have never received this prompt from Rainmeter before but auto updates were working fine. I checked and confirmed the signing cert appears to be valid and from your team so it doesn't seem like its a malicious install of rainmeter, but this is new behavior I haven't seen before, so I declined the prompt and checked what version of Rainmeter is installed. It was 4.5.18. So, then I went to the tray icon and clicked Install rainmeter update, or whatever the option at the top was, and accepted the UAC prompt. This installed the latest release listed on the releases page as of today.

Has something changed with the app that it now triggers UAC with the new releases? I'd like to have the updates happen in the background without my intervention, and without any UAC pop up, as they used to do. What can I do? I am running Windows 11 23H2.

**Comment by brianferguson** [comment]
> Has something changed with the app that it now triggers UAC with the new releases?

Nope.

> I'd like to have the updates happen in the background without my intervention, and without any UAC pop up, as they used to do. What can I do?

UAC prompts happen for any program being installed in your `Program Files` directory. It's been that way for almost 2 decades on Windows (starting with Vista).

The only thing you can do is turn off UAC, which I (nor the Rainmeter Team) recommend.

Or you can install a portable version of Rainmeter.
https://docs.rainmeter.net/manual/installing-rainmeter/#PortableInstallation

Also, some useful information:
https://docs.rainmeter.net/manual/installing-rainmeter/auto-update/#AutoUpdateNotes

-Brian
