### ISSUE TITLE
it doesn't look clear on high dpi displays

### ISSUE THREAD

**Issue by Gr3yPh** [rainmeter/rainmeter#393]
my display's dpi is set to 200%, but the rainmeter on it looks... blurry.

**Comment by brianferguson** [comment]
This has been reported numerous times.
#60, #64, #207, #331, #334, #335

We are very aware of this issue and unfortunately have not had the time to add support for dpi awareness at this time.

Here is a workaround: [https://forum.rainmeter.net/viewtopic.php?t=22272#p118040](https://forum.rainmeter.net/viewtopic.php?t=22272#p118040)

-Brian

**Comment by Gr3yPh** [comment]
well, i did followed these steps and it looks pretty clear but another problem is that the skins are really small now. though some skins are able to change their size, some can't

**Comment by AERVAQR3GZ** [comment]
The same happens for me too. The skin is very small and I am not sure how to fix it.
