### ISSUE TITLE
A more conventional Padding values order.

### ISSUE THREAD

**Issue by DiglidiDudeNG** [rainmeter/rainmeter#44]
This isn't too important, but it has been kinda-sorta bothersome.

I was checking the documentation for the Padding property, and I noticed it was a very unusual order for it's values. (Left, Top, Right, Bottom)

I say It's unusual because if you take CSS, a language that also implements padding in that manner, it goes *Top*, *Right*, *Bottom* and *Left* instead for it's 4-values syntax. 

When it comes to computer coding, it's a very good idea to keep some standards intact to increase the ease of access of similar scripting languages' syntaxes.

Now, I agree that it's problematic when it comes to compatibility, so it all depends on how much the next versions will change things to the point where compatibility will be broken. So feel free to reject it if compability is your priority.

**Comment by poiru** [comment]
Agreed, but unfortunately we are stuck with this now.
