### ISSUE TITLE
AvancedCPU Plugin: Processes with same name will be ignored together

### ISSUE THREAD

**Issue by Dikay900** [rainmeter/rainmeter#5]
Excluding the first top process with name test.exe will also exclude a second process with the same name althought these are different processes named test and test#1 in perfmon.msc

The specific scenario is that i have 4 processes with same name all with the highest processing time but just the first one get shown... (skin enigma/processes for example)

**Comment by brianferguson** [comment]
The AdvancedCPU has now been deprecated. See UsageMonitor: https://docs.rainmeter.net/manual/plugins/usagemonitor/

-Brian
