### ISSUE TITLE
WebParser can't open file if it's used by another process.

### ISSUE THREAD

**Issue by tomkort** [rainmeter/rainmeter#53]
It appears that Wininet can't open a file if it is used by another process. For example when GPU-Z is running, it keeps updating log file at every second, it is not possible to open that file for reading with WebParser plugin. I tested fixing the bug by resorting to std::fstream if the url starts with "file://" and using PathCreateFromUrlA to easily change the url format and it seems to work.

**Comment by poiru** [comment]
Fixed by 262bda7.
