### ISSUE TITLE
Installer command switches broken

### ISSUE THREAD

**Issue by JW0914** [rainmeter/rainmeter#59]
Attempting to utilize command switches for unattended installs results in switches either being completely ignored, or, with the case of the silent switch, < /S >, results in the installer not opening at all.  If attempting to utilize additional switches, once /S is removed, the installer opens to a UI install, however all switches are still ignored.

For example, the following results in nothing occurring (including no temp directory or files in %APPDATA%\Local\Temp):

Rainmeter-3.3-r2468-beta.exe /S /VERSION=64 /PORTABLE=0 /DESKTOPSHORTCUT=0 /STARTUP=1

Whereas this results in all switches being ignored:
Rainmeter-3.3-r2468-beta.exe /VERSION=64 /PORTABLE=0 /DESKTOPSHORTCUT=0 /STARTUP=1 /ALLUSERS=1

This has been occurring for at least as far back as revision 2423.  I performed an LT deployment first week of August and assumed I had simply mistyped a switch when Rainmeter failed to install during the deployment, however, upon updating my deployment with 3.3 r2468, it's apparent it's the installer. 

https://docs.rainmeter.net/manual/installing-rainmeter/

**Comment by thatsIch** [comment]
I just encountered this problem. I tried following the instructions on

https://docs.rainmeter.net/manual/installing-rainmeter/

but this does not seem to work on the latest Rainmeter which on this current point is 

4.0 Beta Release (r2722) from December 4, 2016

I need this to run integration tests with Rainmeter for SublimeRainmeter.

**Comment by brianferguson** [comment]
We removed support for command line switches at the start of the 4.0 beta cycle. At this time we have no plans to add this feature back. Sorry for the inconvenience.

We updated the **beta** docs at the time: https://docs.rainmeter.net/manual-beta/installing-rainmeter/

-Brian

**Comment by JW0914** [comment]
@brianferguson Out of curiosity, why did you guys opt to remove them?  I've never built an installer before, so I'm not sure how tedious or time consuming it is to program the switches into it.

**Comment by brianferguson** [comment]
I don't remember the exact issue, but IIRC it had to do with some file conflicts if a previous installation was found. It would move some files, but not others. @jsmorley or @poiru could probably give a better answer.

-Brian

**Comment by poiru** [comment]
@JW0914 It was half-broken because none of us used it. We decided that maintaining it was not worth the effort especially considering that most of its use cases can be covered by simply redistributing Rainmeter portable installations.

**Comment by aronovgj** [comment]
@poiru 

Chocolatey is a package manager for Windows and it requires silent args to install a software silently.
I am maintaining the Chocolatey package of Rainmeter and I had to hack around that issue by using Autohotkey. This is not guaranteed to always work and it is prone to errors.
[Here](https://forum.rainmeter.net/viewtopic.php?p=111496#p111496) I was encouraged to use the install parameter (I am not ferventcoder, he only took over clearing up the misunderstanding). 
In the link above @jsmorley asked me to change some things in my package. The main problem in the thread I linked was that you don't want Rainmeter to be redistributed (which did not and does not happen anyway). 
I want to comply with what the devs of Rainmeter want. 

> We decided that maintaining it was not worth the effort especially considering that most of its use cases can be covered by simply redistributing Rainmeter portable installations.

This is confusing to me. You are encouraging redistribution and you are encouraging to install portable versions by default. 

I could just unpack the installer but I don't want a second chocolateygate. Please tell me how you would like me to deal with this.

**Comment by thatsIch** [comment]
I used AutoIt to automate it, but this is very error prone since the buttons are not named and you can't use the labels since they depend on the localization.
