### ISSUE TITLE
Add "behind desktop icons" position (especially for Windows 10)

### ISSUE THREAD

**Issue by Diego91b** [rainmeter/rainmeter#61]
It would be great to use Rainmeter as replacement Windows Dreamscene that came with Windows Vista, but this requires the option to run a Rainmeter video player below desktop icons.

Searching the internet I found this page that gives some ideas on how to do:
http://www.codeproject.com/Articles/856020/Draw-Behind-Desktop-Icons-in-Windows

**Comment by brianferguson** [comment]
While it's possible to do this, it isn't a great fit for Rainmeter at this time. As Windows evolves over time, keeping up with 'what works' is just going to be a nightmare. So, until Microsoft allows a native way to draw directly on the desktop, we won't be exploring this.

-Brian
