### ISSUE TITLE
4.0 Beta: Clear log Button on About - Not Really Clearing

### ISSUE THREAD

**Issue by war59312** [rainmeter/rainmeter#62]
Hi,

> OS: Windows 8.1 x64
> 
> Rainmeter: 4.0 beta release (revision 2589)

**Problem**: When I hit the clear button to clear the log on the About screen.

It indeed clears it from display, but that's all. Comes right back when I reopen UI.

**Expected**: I expected the log to be really cleared when I hit the clear button.

Thanks,

Will

**Comment by brianferguson** [comment]
Hi Will,

This is actually the designed behavior of the Clear button. It can be a valuable feature while debugging skins that may throw errors over a period of time.

Here is the conversation about it: [Forum link](https://forum.rainmeter.net/viewtopic.php?p=91367#p91367)

What really happens is that the About dialog's log is not really **thee** log of Rainmeter. Internally, Rainmeter only caches the last 20 messages for the sole purpose of populating the About dialog list when opened. If you close the About dialog and re-open it, the last 20 messages will populate the list again (even if cleared). If the About dialog is left open, it will continue to add items to the list (more then 20).

I am not even sure there would be a good reason to really delete items from the log.

-Brian

**Comment by war59312** [comment]
Makes sense, was just not what I was expecting.

But great rational in this case, so thanks. :D
