### ISSUE TITLE
Russian GUI is too tight

### ISSUE THREAD

**Issue by xtotdam** [rainmeter/rainmeter#64]
Hello!
I use Rainmeter for several years already and like it very much!

But russian GUI is a little bit too tight:
1.  this text field is too small ( I tried to make text in it a little bit shorter (see my today PR #63 ) but barely succeeded )
2. this button is a bit too short. I assume its width is `NUM_BUTTONWIDTH` from 1st line of `Russian.h` but I have no access to Visual Studio and cannot prove it, otherwise it would be in my PR.

![2016-03-19 20 51 45](https://cloud.githubusercontent.com/assets/5108025/13900489/a565ce2e-ee18-11e5-93ab-364d6b341782.png)

**Comment by ActiveColors** [comment]
Looks fine for me. Judging by your buttons at the top-right corner you have adjusted objects size. Navigate to Control Panel\All Control Panel Items\Display and see if the setting is set to 100%
![2](https://cloud.githubusercontent.com/assets/1996029/13902445/243183c2-edfd-11e5-9dbf-95f2f31326e8.PNG)

**Comment by brianferguson** [comment]
Unfortunately Rainmeter is not DPI-aware at the moment, and as a side-effect some common Windows controls will still appear 'larger' then normal. This happens even if you tell Rainmeter to ignore DPI settings.

You can fix this by setting your monitor back to 100% DPI, but obviously this will effect how other programs are drawn on your screen.

-Brian

**Comment by xtotdam** [comment]
Yep, you're right, I use 125% (is perfect for my 21:9). I am glad this is not an issue :)
