### ISSUE TITLE
The newest version of Spotify breaks the plugin

### ISSUE THREAD

**Issue by skwerlman** [rainmeter/rainmeter#83]
I updated Spotify today, and now Spotify.dll no longer returns the artist name, song name or album art.

I have not had time to test other functionality of the plugin to see if any of it still works.

__Spotify Plugin:__
1.2.3.0

__Rainmeter:__
4.0.0 beta r2620 64-bit (Sep  4 2016)
Windows 10 Pro 64-bit (build 14393)
Path: C:\Program Files\Rainmeter\
IniFile: C:\Users\user\AppData\Roaming\Rainmeter\Rainmeter.ini
SkinPath: C:\Users\user\Documents\Rainmeter\Skins\

**Comment by brianferguson** [comment]
The Spotify plugin is a 3rd party plugin. Please contact the author for any fixes.
https://forum.rainmeter.net/viewtopic.php?p=94631#p94631

-Brian

P.S. - You may try the latest release of the plugin which is at version 1.2.4.1

**Comment by skwerlman** [comment]
I hadn't realized it was separate; whoops.

Thanks for pointing me in the right direction.
