### ISSUE TITLE
Impossible to load fully dynamic skins

### ISSUE THREAD

**Issue by skwerlman** [rainmeter/rainmeter#84]
I have a visualizer skin where all of the meters are created on load using a factory script. Unless I prepopulate one of the dynamically generated includes, rainmeter refuses to even try to load the script, stating that it contains no meters and is therefore not valid.

If the script had been allowed to update just once, all of the meters for the visualizer would have loaded. Would it be possible to delay checking for meters in a skin by one update?

__Rainmeter:__
4.0.0 beta r2620 64-bit (Sep  4 2016)
Windows 10 Pro 64-bit (build 14393)
Path: C:\Program Files\Rainmeter\
IniFile: C:\Users\user\AppData\Roaming\Rainmeter\Rainmeter.ini
SkinPath: C:\Users\user\Documents\Rainmeter\Skins\

**Comment by brianferguson** [comment]
Not likely, at least not in the near future. While possible code-wise, we really don't have any intent to have scripts 'build' skins at this time.

As a work-around, you could create a 'dummy' meter in your skin to avoid the error message. Something like the following:
[Dummy]
Meter=String

You don't need anymore options then that, and it won't have any noticeable impact on performance.

-Brian
