### ISSUE TITLE
Google Play Music Desktop Player Support

### ISSUE THREAD

**Issue by powerjbn** [rainmeter/rainmeter#86]
It would be nice to have support for Google Play Music in the form of the [unofficial Google Play Music Desktop Player](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-), as I've seen quite a few people who are trying to find a way to control Google Play Music through Rainmeter, and can't, despite the fact that the GPMDP has a documented API for doing exactly this sort of thing.

**Comment by tjhrulz** [comment]
While my support is not official, I have made a plugin for it here: https://github.com/tjhrulz/GPMDP-Plugin/releases.

**Comment by brianferguson** [comment]
We have no plans to officially support this via NowPlaying (assuming that is what you are asking).

-Brian
