### ISSUE TITLE
Downloading something in background?

### ISSUE THREAD

**Issue by JoseGalRe** [rainmeter/rainmeter#88]
Hi guys, i have a question, v4.0.0.2746, have unknown downloads in background? 

in the v3.3.2.2743, no problems, no downloads in background

![alt text](http://i.imgur.com/zP0XbfL.png)

Windows 10 (10.0.14393.576) x64

**Comment by brianferguson** [comment]
What you are seeing is how Rainmeter checks for a new version on startup.
https://docs.rainmeter.net/manual/user-interface/manage/#General

![manage](https://cloud.githubusercontent.com/assets/1591640/21584492/8d6bab5c-d078-11e6-9997-cec7394edb78.png)

-Brian
