### ISSUE TITLE
[REQ] New AdvancedMemory Plugin

### ISSUE THREAD

**Issue by freMea** [rainmeter/rainmeter#90]
Hi,

Just like the AdvancedCPU plugin, we need a plugin to do the same for memory usage (Working Set - Private) by process.

It will allow us to create skins showing top processes by memory usage.

An option to group processes with same name (i.e.: chrome.exe) will be useful. So for example, 3 processes like:
```
chrome.exe 10 MB
chrome.exe 20 MB
chrome.exe 30 MB
```
could be retrieved in one measure that would sum the values and we could finally get:
`chrome.exe 60MB`

Regards

**Comment by brianferguson** [comment]
We recently add [UsageMonitor](https://docs.rainmeter.net/manual-beta/plugins/usagemonitor/).

-Brian
