### ISSUE TITLE
Regression of clear log potentially due to Win10

### ISSUE THREAD

**Issue by thatsIch** [rainmeter/rainmeter#95]
I just installed every release since [2708](https://github.com/rainmeter/rainmeter/releases/tag/v4.0.0.2708) which was the latest one I used regarding for features and noticed that I was not able to clear the log anymore up to the latest 4.0 release this year. 

After clearing the log the display log is cleared, but after closing the dialog and reopening it, the old information are still displayed. It seems it displays the startup log of Rainmeter. 

I made a friend of mine test it on his setup and it concluded the same behavior.

Steps to reproduce:
* run Rainmeter
* open about
* click clear protocol
* close dialog
* open about

Expected behavior:
It should clear the protocol

Due to localization it is possible, that the steps are labeled differently (translating it from German).

I wonder if this is due to windows 10/windows 10 update because I am sure, that a prior version of Rainmeter worked.

**Comment by brianferguson** [comment]
See #62 

-Brian

**Comment by thatsIch** [comment]
so as far as I understand there are 3 copies of the log?

* one internal
* one wrote to .log if checked
* one to about panel

Never expected it to be implemented like that. Thanks for clarification
