### ISSUE TITLE
Cannot install rainmeter 4.0 on Windows Server 2008 R2

### ISSUE THREAD

**Issue by Xeollron** [rainmeter/rainmeter#96]
I am using Windows Server 2008 R2 Enterprise 64-bit (build 7601) Service Pack 1 (this is the server release of Windows 7)
It is currently running rainmeter 3.3.2 r2609 64-bit
When I run the 4.0 installer exe I get the error
"Rainmeter 4.0 requires at least Windows 7 with Service Pack 1."

**Comment by brianferguson** [comment]
Fixed as of [8903385](https://github.com/rainmeter/rainmeter/commit/8903385a8d2311476905950cfe94e8c2206f3599).

Thanks for reporting.

-Brian
